upload:
  path: /forum/plaatjes/upload
  controller: CsrDelft\controller\ForumPlaatjesController::upload
  methods: [GET,POST]
  defaults: { _mag: P_LOGGED_IN }
bekijken:
  path: /forum/plaatjes/bekijken/{id}
  controller: CsrDelft\controller\ForumPlaatjesController::bekijken
  methods: GET
  requirements: { id: '[a-zA-Z0-9]*' }
  defaults: { _mag: P_LOGGED_IN }
bekijken-resized:
  path: /forum/plaatjes/bekijken/{id}/resized
  controller: CsrDelft\controller\ForumPlaatjesController::bekijken
  methods: GET
  requirements: { id: '[a-zA-Z0-9]*' }
  defaults: { _mag: P_LOGGED_IN, resized: true }
