profiel-profiel:
  path: /profiel/{uid}
  controller: CsrDelft\controller\ProfielController::profiel
  methods: GET
  defaults: { uid: null, _mag: P_OUDLEDEN_READ }
  requirements: { uid: '.{4}' }

profiel-bewerken:
  path: /profiel/{uid}/bewerken
  controller: CsrDelft\controller\ProfielController::bewerken
  methods: [GET,POST]
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_PROFIEL_EDIT }

profiel-voorkeuren:
  path: /profiel/{uid}/voorkeuren
  controller: CsrDelft\controller\ProfielController::voorkeuren
  methods: [GET,POST]
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_PROFIEL_EDIT }

profiel-voorkeuren-redirect:
  path: /profiel/voorkeuren
  controller: CsrDelft\controller\ProfielController::redirectWithUid
  methods: [GET]
  defaults:
    route: profiel-voorkeuren
    _mag: P_PROFIEL_EDIT

profiel-reset-private-token:
  path: /profiel/{uid}/resetPrivateToken
  controller: CsrDelft\controller\ProfielController::resetPrivateToken
  methods: GET
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_PROFIEL_EDIT }

profiel-add-to-google-contacts:
  path: /profiel/{uid}/addToGoogleContacts
  controller: CsrDelft\controller\ProfielController::addToGoogleContacts
  methods: GET
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_LEDEN_READ }

profiel-nieuw:
  path: /profiel/{lidjaar}/nieuw/{status}
  controller: CsrDelft\controller\ProfielController::nieuw
  methods: [GET,POST]
  requirements: { uid: '.{4}' }
  defaults: { _mag: "P_LEDEN_MOD,commissie:NovCie" }

profiel-stamboom:
  path: /profiel/{uid}/stamboom
  controller: CsrDelft\controller\ProfielController::stamboom
  methods: GET
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_OUDLEDEN_READ }

profiel-saldo:
  path: /profiel/{uid}/saldo/{timespan}
  controller: CsrDelft\controller\ProfielController::saldo
  methods: POST
  requirements: { uid: '.{4}', timespan: '\d+' }
  defaults: { _mag: P_LEDEN_READ }

profiel-pasfoto-default:
  path: /profiel/pasfoto/{uid}.jpg
  controller: CsrDelft\controller\PasfotoController::pasfoto
  methods: GET
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_LEDEN_READ }

profiel-pasfoto:
  path: /profiel/pasfoto/{uid}.{vorm}.jpg
  controller: CsrDelft\controller\PasfotoController::pasfoto
  methods: GET
  requirements: { uid: '.{4}' }
  defaults: { type: 'civitas', _mag: P_LEDEN_READ }

profiel-vcard:
  path: /profiel/{uid}.vcf
  controller: CsrDelft\controller\ProfielController::vcard
  methods: GET
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_LEDEN_READ }

profiel-kaartje:
  path: /profiel/{uid}/kaartje
  controller: CsrDelft\controller\ProfielController::kaartje
  methods: GET
  requirements: { uid: '.{4}' }
  defaults: { _mag: P_LEDEN_READ }
