rechten-bekijken:
  path: /rechten/bekijken/{environment}/{resource}
  controller: CsrDelft\controller\RechtenController::bekijken
  methods: GET
  defaults: { _mag: P_LOGGED_IN, environment: null, resource: null }

rechten-data:
  path: /rechten/bekijken/{environment}/{resource}
  controller: CsrDelft\controller\RechtenController::data
  methods: POST
  defaults: { _mag: P_LOGGED_IN, environment: null, resource: null }

rechten-aanmaken:
  path: /rechten/aanmaken/{environment}/{resource}
  controller: CsrDelft\controller\RechtenController::aanmaken
  methods: POST
  defaults: { _mag: P_LOGGED_IN, environment: null, resource: null }

rechten-verwijderen:
  path: /rechten/verwijderen
  controller: CsrDelft\controller\RechtenController::verwijderen
  methods: POST
  defaults: { _mag: P_LOGGED_IN }

rechten-wijzigen:
  path: /rechten/wijzigen
  controller: CsrDelft\controller\RechtenController::wijzigen
  methods: POST
  defaults: { _mag: P_LOGGED_IN }

