web_profiler_wdt:
  resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
  prefix: /_wdt
  defaults:
    _csrfUnsafe: true
    _mag: PUBLIC_ACCESS

web_profiler_profiler:
  resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
  prefix: /_profiler
  defaults:
    _csrfUnsafe: true
    _mag: PUBLIC_ACCESS
