<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20210417170454 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Ruim de oude groepen tabellen op';
	}

	public function up(Schema $schema): void
	{
		$this->addSql('ALTER TABLE activiteit_deelnemers DROP FOREIGN KEY FK_7F206BAB9EB44EC5');
		$this->addSql('ALTER TABLE bestuurs_leden DROP FOREIGN KEY FK_7BE62A789EB44EC5');
		$this->addSql('ALTER TABLE commissie_leden DROP FOREIGN KEY FK_18A4E69E9EB44EC5');
		$this->addSql('ALTER TABLE groep_leden DROP FOREIGN KEY FK_47D1C06D9EB44EC5');
		$this->addSql('ALTER TABLE ketzer_deelnemers DROP FOREIGN KEY FK_E29708B29EB44EC5');
		$this->addSql('ALTER TABLE kring_leden DROP FOREIGN KEY FK_C1C295369EB44EC5');
		$this->addSql('ALTER TABLE lichting_leden DROP FOREIGN KEY FK_9F803B119EB44EC5');
		$this->addSql('ALTER TABLE ondervereniging_leden DROP FOREIGN KEY FK_7EC7AEBA9EB44EC5');
		$this->addSql('ALTER TABLE verticale_leden DROP FOREIGN KEY FK_52C85C389EB44EC5');
		$this->addSql('ALTER TABLE werkgroep_deelnemers DROP FOREIGN KEY FK_38E14A6B9EB44EC5');
		$this->addSql('ALTER TABLE bewoners DROP FOREIGN KEY FK_62C774019EB44EC5');

		$this->addSql('DROP TABLE activiteit_deelnemers');
		$this->addSql('DROP TABLE activiteiten');
		$this->addSql('DROP TABLE besturen');
		$this->addSql('DROP TABLE bestuurs_leden');
		$this->addSql('DROP TABLE bewoners');
		$this->addSql('DROP TABLE commissie_leden');
		$this->addSql('DROP TABLE commissies');
		$this->addSql('DROP TABLE groep_leden');
		$this->addSql('DROP TABLE groepen');
		$this->addSql('DROP TABLE ketzer_deelnemers');
		$this->addSql('DROP TABLE ketzers');
		$this->addSql('DROP TABLE kring_leden');
		$this->addSql('DROP TABLE kringen');
		$this->addSql('DROP TABLE lichting_leden');
		$this->addSql('DROP TABLE lichtingen');
		$this->addSql('DROP TABLE ondervereniging_leden');
		$this->addSql('DROP TABLE onderverenigingen');
		$this->addSql('DROP TABLE verticale_leden');
		$this->addSql('DROP TABLE verticalen');
		$this->addSql('DROP TABLE werkgroep_deelnemers');
		$this->addSql('DROP TABLE werkgroepen');
		$this->addSql('DROP TABLE woonoorden');
	}

	public function down(Schema $schema): void
	{
		$this->addSql('CREATE TABLE activiteit_deelnemers (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, opmerking VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lid_sinds DATETIME NOT NULL, INDEX lid_sinds (lid_sinds), INDEX IDX_7F206BAB539B0606 (uid), INDEX IDX_7F206BAB97983E4 (door_uid), INDEX IDX_7F206BAB9EB44EC5 (groep_id), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE activiteiten (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, aanmeld_limiet INT DEFAULT NULL, aanmelden_vanaf DATETIME NOT NULL, aanmelden_tot DATETIME NOT NULL, bewerken_tot DATETIME DEFAULT NULL, afmelden_tot DATETIME DEFAULT NULL, soort VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, rechten_aanmelden VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, locatie VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, in_agenda TINYINT(1) NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, omschrijving LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, keuzelijst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX in_agenda (in_agenda), INDEX soort (soort), INDEX status (status), INDEX IDX_1C50895F3A4A27C1 (maker_uid), INDEX familie (familie), INDEX begin_moment (begin_moment), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE besturen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, bijbeltekst LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, omschrijving LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, keuzelijst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX begin_moment (begin_moment), INDEX IDX_16921DA03A4A27C1 (maker_uid), INDEX familie (familie), INDEX status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE bestuurs_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, opmerking VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lid_sinds DATETIME NOT NULL, INDEX lid_sinds (lid_sinds), INDEX IDX_7BE62A78539B0606 (uid), INDEX IDX_7BE62A7897983E4 (door_uid), INDEX IDX_7BE62A789EB44EC5 (groep_id), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE bewoners (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, opmerking VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lid_sinds DATETIME NOT NULL, INDEX lid_sinds (lid_sinds), INDEX IDX_62C77401539B0606 (uid), INDEX IDX_62C7740197983E4 (door_uid), INDEX IDX_62C774019EB44EC5 (groep_id), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE commissie_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, opmerking VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lid_sinds DATETIME NOT NULL, INDEX lid_sinds (lid_sinds), INDEX IDX_18A4E69E539B0606 (uid), INDEX IDX_18A4E69E97983E4 (door_uid), INDEX IDX_18A4E69E9EB44EC5 (groep_id), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE commissies (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, soort VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, omschrijving LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, keuzelijst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX familie (familie), INDEX begin_moment (begin_moment), INDEX IDX_858C850B3A4A27C1 (maker_uid), INDEX soort (soort), INDEX status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE groep_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, opmerking VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lid_sinds DATETIME NOT NULL, INDEX lid_sinds (lid_sinds), INDEX IDX_47D1C06D539B0606 (uid), INDEX IDX_47D1C06D97983E4 (door_uid), INDEX IDX_47D1C06D9EB44EC5 (groep_id), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE groepen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, rechten_aanmelden VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, omschrijving LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, keuzelijst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX familie (familie), INDEX IDX_647C5D9F3A4A27C1 (maker_uid), INDEX status (status), INDEX begin_moment (begin_moment), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE ketzer_deelnemers (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, opmerking VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lid_sinds DATETIME NOT NULL, INDEX lid_sinds (lid_sinds), INDEX IDX_E29708B2539B0606 (uid), INDEX IDX_E29708B297983E4 (door_uid), INDEX IDX_E29708B29EB44EC5 (groep_id), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE ketzers (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, aanmeld_limiet INT DEFAULT NULL, aanmelden_vanaf DATETIME NOT NULL, aanmelden_tot DATETIME NOT NULL, bewerken_tot DATETIME DEFAULT NULL, afmelden_tot DATETIME DEFAULT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, omschrijving LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, keuzelijst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX begin_moment (begin_moment), INDEX IDX_DE2D6D463A4A27C1 (maker_uid), INDEX familie (familie), INDEX status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE kring_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, opmerking VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lid_sinds DATETIME NOT NULL, INDEX lid_sinds (lid_sinds), INDEX IDX_C1C29536539B0606 (uid), INDEX IDX_C1C2953697983E4 (door_uid), INDEX IDX_C1C295369EB44EC5 (groep_id), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE kringen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, verticale CHAR(1) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, kring_nummer INT NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, omschrijving LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, keuzelijst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX verticale (verticale), INDEX kring_nummer (kring_nummer), INDEX IDX_E2F4F0BF3A4A27C1 (maker_uid), INDEX familie (familie), INDEX begin_moment (begin_moment), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE lichting_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, opmerking VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lid_sinds DATETIME NOT NULL, INDEX lid_sinds (lid_sinds), INDEX IDX_9F803B11539B0606 (uid), INDEX IDX_9F803B1197983E4 (door_uid), INDEX IDX_9F803B119EB44EC5 (groep_id), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE lichtingen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, lidjaar INT NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, omschrijving LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, keuzelijst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX status (status), INDEX begin_moment (begin_moment), UNIQUE INDEX UNIQ_1EDCCA6E4D508A76 (lidjaar), INDEX familie (familie), INDEX IDX_1EDCCA6E3A4A27C1 (maker_uid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE ondervereniging_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, opmerking VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lid_sinds DATETIME NOT NULL, INDEX lid_sinds (lid_sinds), INDEX IDX_7EC7AEBA539B0606 (uid), INDEX IDX_7EC7AEBA97983E4 (door_uid), INDEX IDX_7EC7AEBA9EB44EC5 (groep_id), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE onderverenigingen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, soort VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, omschrijving LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, keuzelijst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX soort (soort), INDEX status (status), INDEX IDX_F1E76283A4A27C1 (maker_uid), INDEX familie (familie), INDEX begin_moment (begin_moment), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE verticale_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, opmerking VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lid_sinds DATETIME NOT NULL, INDEX lid_sinds (lid_sinds), INDEX IDX_52C85C38539B0606 (uid), INDEX IDX_52C85C3897983E4 (door_uid), INDEX IDX_52C85C389EB44EC5 (groep_id), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE verticalen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, letter CHAR(1) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, omschrijving LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, keuzelijst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX familie (familie), INDEX IDX_79C519073A4A27C1 (maker_uid), INDEX status (status), UNIQUE INDEX UNIQ_79C519078E02EE0A (letter), INDEX begin_moment (begin_moment), UNIQUE INDEX UNIQ_79C51907FC4DB938 (naam), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE werkgroep_deelnemers (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, opmerking VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, lid_sinds DATETIME NOT NULL, INDEX lid_sinds (lid_sinds), INDEX IDX_38E14A6B539B0606 (uid), INDEX IDX_38E14A6B97983E4 (door_uid), INDEX IDX_38E14A6B9EB44EC5 (groep_id), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE werkgroepen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, aanmeld_limiet INT DEFAULT NULL, aanmelden_vanaf DATETIME NOT NULL, aanmelden_tot DATETIME NOT NULL, bewerken_tot DATETIME DEFAULT NULL, afmelden_tot DATETIME DEFAULT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, omschrijving LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, keuzelijst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX familie (familie), INDEX IDX_2194ECF73A4A27C1 (maker_uid), INDEX status (status), INDEX begin_moment (begin_moment), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('CREATE TABLE woonoorden (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, soort ENUM(\'w\', \'h\') COMMENT \'(DC2Type:enumHuisStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumHuisStatus)\', eetplan TINYINT(1) NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, omschrijving LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, keuzelijst VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci` COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX status (status), INDEX IDX_782FB8083A4A27C1 (maker_uid), INDEX begin_moment (begin_moment), INDEX familie (familie), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
		$this->addSql('ALTER TABLE activiteit_deelnemers ADD CONSTRAINT FK_7F206BAB539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE activiteit_deelnemers ADD CONSTRAINT FK_7F206BAB97983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE activiteit_deelnemers ADD CONSTRAINT FK_7F206BAB9EB44EC5 FOREIGN KEY (groep_id) REFERENCES activiteiten (id)');
		$this->addSql('ALTER TABLE activiteiten ADD CONSTRAINT FK_1C50895F3A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE besturen ADD CONSTRAINT FK_16921DA03A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE bestuurs_leden ADD CONSTRAINT FK_7BE62A78539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE bestuurs_leden ADD CONSTRAINT FK_7BE62A7897983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE bestuurs_leden ADD CONSTRAINT FK_7BE62A789EB44EC5 FOREIGN KEY (groep_id) REFERENCES besturen (id)');
		$this->addSql('ALTER TABLE bewoners ADD CONSTRAINT FK_62C77401539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE bewoners ADD CONSTRAINT FK_62C7740197983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE bewoners ADD CONSTRAINT FK_62C774019EB44EC5 FOREIGN KEY (groep_id) REFERENCES woonoorden (id)');
		$this->addSql('ALTER TABLE commissie_leden ADD CONSTRAINT FK_18A4E69E539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE commissie_leden ADD CONSTRAINT FK_18A4E69E97983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE commissie_leden ADD CONSTRAINT FK_18A4E69E9EB44EC5 FOREIGN KEY (groep_id) REFERENCES commissies (id)');
		$this->addSql('ALTER TABLE commissies ADD CONSTRAINT FK_858C850B3A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE groep_leden ADD CONSTRAINT FK_47D1C06D539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE groep_leden ADD CONSTRAINT FK_47D1C06D97983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE groep_leden ADD CONSTRAINT FK_47D1C06D9EB44EC5 FOREIGN KEY (groep_id) REFERENCES groepen (id)');
		$this->addSql('ALTER TABLE groepen ADD CONSTRAINT FK_647C5D9F3A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE ketzer_deelnemers ADD CONSTRAINT FK_E29708B2539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE ketzer_deelnemers ADD CONSTRAINT FK_E29708B297983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE ketzer_deelnemers ADD CONSTRAINT FK_E29708B29EB44EC5 FOREIGN KEY (groep_id) REFERENCES ketzers (id)');
		$this->addSql('ALTER TABLE ketzers ADD CONSTRAINT FK_DE2D6D463A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE kring_leden ADD CONSTRAINT FK_C1C29536539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE kring_leden ADD CONSTRAINT FK_C1C2953697983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE kring_leden ADD CONSTRAINT FK_C1C295369EB44EC5 FOREIGN KEY (groep_id) REFERENCES kringen (id)');
		$this->addSql('ALTER TABLE kringen ADD CONSTRAINT FK_E2F4F0BF3A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE lichting_leden ADD CONSTRAINT FK_9F803B11539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE lichting_leden ADD CONSTRAINT FK_9F803B1197983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE lichting_leden ADD CONSTRAINT FK_9F803B119EB44EC5 FOREIGN KEY (groep_id) REFERENCES lichtingen (id)');
		$this->addSql('ALTER TABLE lichtingen ADD CONSTRAINT FK_1EDCCA6E3A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE ondervereniging_leden ADD CONSTRAINT FK_7EC7AEBA539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE ondervereniging_leden ADD CONSTRAINT FK_7EC7AEBA97983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE ondervereniging_leden ADD CONSTRAINT FK_7EC7AEBA9EB44EC5 FOREIGN KEY (groep_id) REFERENCES onderverenigingen (id)');
		$this->addSql('ALTER TABLE onderverenigingen ADD CONSTRAINT FK_F1E76283A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE verticale_leden ADD CONSTRAINT FK_52C85C38539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE verticale_leden ADD CONSTRAINT FK_52C85C3897983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE verticale_leden ADD CONSTRAINT FK_52C85C389EB44EC5 FOREIGN KEY (groep_id) REFERENCES verticalen (id)');
		$this->addSql('ALTER TABLE verticalen ADD CONSTRAINT FK_79C519073A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE werkgroep_deelnemers ADD CONSTRAINT FK_38E14A6B539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE werkgroep_deelnemers ADD CONSTRAINT FK_38E14A6B97983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE werkgroep_deelnemers ADD CONSTRAINT FK_38E14A6B9EB44EC5 FOREIGN KEY (groep_id) REFERENCES werkgroepen (id)');
		$this->addSql('ALTER TABLE werkgroepen ADD CONSTRAINT FK_2194ECF73A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE woonoorden ADD CONSTRAINT FK_782FB8083A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
	}
}
