<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20200705132858 extends AbstractMigration {
	public function getDescription(): string {
		return 'Initiele database migratie';
	}

	public function up(Schema $schema): void {
		$this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

		$this->addSql('CREATE TABLE login_sessions (session_hash VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, login_moment DATETIME NOT NULL, expire DATETIME NOT NULL, user_agent VARCHAR(255) NOT NULL, ip VARCHAR(255) NOT NULL, lock_ip TINYINT(1) NOT NULL, authentication_method VARCHAR(255) NOT NULL, INDEX IDX_B4C4BD8C539B0606 (uid), PRIMARY KEY(session_hash)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE accounts (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, username VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, email VARCHAR(255) NOT NULL, pass_hash VARCHAR(255) NOT NULL, pass_since DATETIME NOT NULL, last_login_success DATETIME DEFAULT NULL, last_login_attempt DATETIME DEFAULT NULL, failed_login_attempts INT NOT NULL, blocked_reason LONGTEXT DEFAULT NULL, perm_role VARCHAR(255) NOT NULL, private_token VARCHAR(255) DEFAULT NULL, private_token_since DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_CAC89EACF85E0677 (username), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE login_remember (id INT AUTO_INCREMENT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, token VARCHAR(255) NOT NULL, remember_since DATETIME NOT NULL, device_name VARCHAR(255) NOT NULL, ip VARCHAR(255) NOT NULL, lock_ip TINYINT(1) NOT NULL, INDEX IDX_BD5B5182539B0606 (uid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE profielen (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, patroon VARCHAR(4) COMMENT \'(DC2Type:uid)\' DEFAULT NULL, changelog TEXT COMMENT \'(DC2Type:changelog)\' NOT NULL, voornamen VARCHAR(255) DEFAULT NULL, voorletters VARCHAR(255) NOT NULL, voornaam VARCHAR(255) NOT NULL, tussenvoegsel VARCHAR(255) DEFAULT NULL, achternaam VARCHAR(255) NOT NULL, postfix VARCHAR(255) DEFAULT NULL, nickname VARCHAR(255) DEFAULT NULL, duckname VARCHAR(255) DEFAULT NULL, geslacht ENUM(\'m\', \'v\') COMMENT \'(DC2Type:enumGeslacht)\' NOT NULL COMMENT \'(DC2Type:enumGeslacht)\', gebdatum DATE NOT NULL, sterfdatum DATE DEFAULT NULL, lengte INT NOT NULL, echtgenoot VARCHAR(4) COMMENT \'(DC2Type:uid)\' DEFAULT NULL, adresseringechtpaar VARCHAR(255) DEFAULT NULL, ontvangtcontactueel ENUM(\'ja\', \'digitaal\', \'nee\') COMMENT \'(DC2Type:enumOntvangtContactueel)\' NOT NULL COMMENT \'(DC2Type:enumOntvangtContactueel)\', adres VARCHAR(255) NOT NULL, postcode VARCHAR(255) NOT NULL, woonplaats VARCHAR(255) NOT NULL, land VARCHAR(255) NOT NULL, telefoon VARCHAR(255) DEFAULT NULL, o_adres VARCHAR(255) DEFAULT NULL, o_postcode VARCHAR(255) DEFAULT NULL, o_woonplaats VARCHAR(255) DEFAULT NULL, o_land VARCHAR(255) DEFAULT NULL, o_telefoon VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, sec_email VARCHAR(255) DEFAULT NULL, mobiel VARCHAR(255) DEFAULT NULL, linkedin VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, studie VARCHAR(255) DEFAULT NULL, studiejaar VARCHAR(255) DEFAULT NULL, beroep VARCHAR(255) DEFAULT NULL, lidjaar INT NOT NULL, lidafdatum DATE DEFAULT NULL, status VARCHAR(255) NOT NULL, bankrekening VARCHAR(255) DEFAULT NULL, machtiging TINYINT(1) DEFAULT NULL, moot VARCHAR(255) DEFAULT NULL, verticale VARCHAR(255) DEFAULT NULL, verticaleleider TINYINT(1) DEFAULT NULL, kringcoach TINYINT(1) DEFAULT NULL, eetwens VARCHAR(255) DEFAULT NULL, corvee_punten INT DEFAULT NULL, corvee_punten_bonus INT DEFAULT NULL, novitiaat LONGTEXT DEFAULT NULL, novitiaatBijz LONGTEXT DEFAULT NULL, medisch LONGTEXT DEFAULT NULL, startkamp VARCHAR(255) DEFAULT NULL, matrixPlek VARCHAR(255) DEFAULT NULL, novietSoort VARCHAR(255) DEFAULT NULL, kgb LONGTEXT DEFAULT NULL, vrienden LONGTEXT DEFAULT NULL, middelbareSchool VARCHAR(255) DEFAULT NULL, profielOpties VARCHAR(255) DEFAULT NULL, kerk VARCHAR(255) DEFAULT NULL, muziek VARCHAR(255) DEFAULT NULL, zingen VARCHAR(255) DEFAULT NULL, INDEX IDX_301B6229742C4A98 (patroon), INDEX voornaam (voornaam), INDEX achternaam (achternaam), INDEX verticale (verticale), INDEX nickname (nickname), INDEX status (status), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE CiviLog (id INT AUTO_INCREMENT NOT NULL, ip VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, data LONGTEXT NOT NULL, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE CiviSaldo (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, naam LONGTEXT NOT NULL, saldo INT NOT NULL, laatst_veranderd DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, deleted TINYINT(1) DEFAULT \'0\' NOT NULL, PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE mlt_aanmeldingen (maaltijd_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' DEFAULT NULL, door_abonnement INT DEFAULT NULL, aantal_gasten INT NOT NULL, gasten_eetwens VARCHAR(255) DEFAULT NULL, laatst_gewijzigd DATETIME NOT NULL, INDEX IDX_B156D32F539B0606 (uid), INDEX IDX_B156D32FCBA49CBE (maaltijd_id), INDEX IDX_B156D32F97983E4 (door_uid), INDEX IDX_B156D32F19F42197 (door_abonnement), PRIMARY KEY(maaltijd_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE mlt_maaltijden (maaltijd_id INT AUTO_INCREMENT NOT NULL, mlt_repetitie_id INT DEFAULT NULL, product_id INT NOT NULL, titel VARCHAR(255) NOT NULL, aanmeld_limiet INT NOT NULL, datum DATE NOT NULL, tijd TIME NOT NULL COMMENT \'(DC2Type:time_immutable)\', gesloten TINYINT(1) NOT NULL, laatst_gesloten DATETIME DEFAULT NULL, verwijderd TINYINT(1) NOT NULL, aanmeld_filter VARCHAR(255) DEFAULT NULL, omschrijving LONGTEXT DEFAULT NULL, verwerkt TINYINT(1) NOT NULL, INDEX IDX_20DD1727A8500550 (mlt_repetitie_id), INDEX IDX_20DD17274584665A (product_id), PRIMARY KEY(maaltijd_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE mlt_repetities (mlt_repetitie_id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, dag_vd_week INT NOT NULL, periode_in_dagen INT NOT NULL, standaard_titel VARCHAR(255) NOT NULL, standaard_tijd TIME NOT NULL COMMENT \'(DC2Type:time_immutable)\', standaard_prijs INT DEFAULT NULL, abonneerbaar TINYINT(1) NOT NULL, standaard_limiet INT NOT NULL, abonnement_filter VARCHAR(255) DEFAULT NULL, INDEX IDX_5505370E4584665A (product_id), PRIMARY KEY(mlt_repetitie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE mlt_abonnementen (mlt_repetitie_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, wanneer_ingeschakeld DATETIME NOT NULL, INDEX IDX_CA961AB0A8500550 (mlt_repetitie_id), PRIMARY KEY(mlt_repetitie_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE mlt_archief (maaltijd_id INT AUTO_INCREMENT NOT NULL, titel VARCHAR(255) NOT NULL, datum DATE NOT NULL, tijd TIME NOT NULL COMMENT \'(DC2Type:time_immutable)\', prijs INT NOT NULL, aanmeldingen LONGTEXT NOT NULL, PRIMARY KEY(maaltijd_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE crv_taken (taak_id INT AUTO_INCREMENT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' DEFAULT NULL, maaltijd_id INT DEFAULT NULL, crv_repetitie_id INT DEFAULT NULL, functie_id INT NOT NULL, datum DATE NOT NULL, punten INT NOT NULL, bonus_malus INT NOT NULL, punten_toegekend INT NOT NULL, bonus_toegekend INT NOT NULL, wanneer_toegekend DATETIME DEFAULT NULL, wanneer_gemaild LONGTEXT DEFAULT NULL, verwijderd TINYINT(1) NOT NULL, INDEX IDX_66384104539B0606 (uid), INDEX IDX_66384104C0ADB06C (crv_repetitie_id), INDEX IDX_66384104CBA49CBE (maaltijd_id), INDEX IDX_663841046B113FD2 (functie_id), PRIMARY KEY(taak_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE crv_repetities (crv_repetitie_id INT AUTO_INCREMENT NOT NULL, mlt_repetitie_id INT DEFAULT NULL, functie_id INT NOT NULL, dag_vd_week INT NOT NULL, periode_in_dagen INT NOT NULL, standaard_punten INT NOT NULL, standaard_aantal INT DEFAULT NULL, voorkeurbaar TINYINT(1) NOT NULL, INDEX IDX_3C44567BA8500550 (mlt_repetitie_id), INDEX IDX_3C44567B6B113FD2 (functie_id), PRIMARY KEY(crv_repetitie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE crv_functies (functie_id INT AUTO_INCREMENT NOT NULL, naam VARCHAR(255) NOT NULL, afkorting VARCHAR(255) NOT NULL, email_bericht LONGTEXT NOT NULL, standaard_punten INT NOT NULL, kwalificatie_benodigd TINYINT(1) NOT NULL, maaltijden_sluiten TINYINT(1) NOT NULL, PRIMARY KEY(functie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE CiviProduct (id INT AUTO_INCREMENT NOT NULL, categorie_id INT NOT NULL, status INT NOT NULL, beschrijving LONGTEXT NOT NULL, prioriteit INT NOT NULL, beheer TINYINT(1) NOT NULL, INDEX IDX_C4590238BCF5E72D (categorie_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE CiviBestellingInhoud (bestelling_id INT NOT NULL, product_id INT NOT NULL, aantal INT NOT NULL, INDEX IDX_30A7C75CA2E63037 (bestelling_id), INDEX IDX_30A7C75C4584665A (product_id), PRIMARY KEY(bestelling_id, product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE CiviBestelling (id INT AUTO_INCREMENT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, totaal INT DEFAULT 0 NOT NULL, deleted TINYINT(1) DEFAULT \'0\' NOT NULL, moment DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, comment VARCHAR(255) DEFAULT NULL, cie VARCHAR(255) NOT NULL, INDEX IDX_290D88AC539B0606 (uid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE CiviPrijs (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, van DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, tot DATETIME DEFAULT NULL, prijs INT NOT NULL, INDEX IDX_86CCDFA74584665A (product_id), UNIQUE INDEX unique_van_product_id (van, product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE CiviCategorie (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL, status INT NOT NULL, cie VARCHAR(255) NOT NULL, INDEX cie (cie), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE biebexemplaar (id INT AUTO_INCREMENT NOT NULL, boek_id INT DEFAULT 0 NOT NULL, eigenaar_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, uitgeleend_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' DEFAULT NULL, opmerking LONGTEXT NOT NULL, toegevoegd DATETIME NOT NULL, status ENUM(\'beschikbaar\', \'uitgeleend\', \'teruggegeven\', \'vermist\') COMMENT \'(DC2Type:enumBoekExemplaarStatus)\' NOT NULL COMMENT \'(DC2Type:enumBoekExemplaarStatus)\', uitleendatum DATETIME DEFAULT NULL, leningen INT DEFAULT 0 NOT NULL, INDEX IDX_27CEE3A452DCF440 (eigenaar_uid), INDEX IDX_27CEE3A4C5564237 (uitgeleend_uid), INDEX IDX_27CEE3A45C12AB20 (boek_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE biebboek (id INT AUTO_INCREMENT NOT NULL, categorie_id INT DEFAULT NULL, auteur_id INT DEFAULT 0 NOT NULL, titel VARCHAR(255) NOT NULL, auteur VARCHAR(255) NOT NULL, uitgavejaar INT NOT NULL, uitgeverij VARCHAR(255) NOT NULL, paginas INT DEFAULT NULL, taal VARCHAR(255) NOT NULL, isbn VARCHAR(255) DEFAULT NULL, code VARCHAR(255) NOT NULL, INDEX IDX_42475FFA60BB6FE6 (auteur_id), INDEX IDX_42475FFABCF5E72D (categorie_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE lidtoestemmingen (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, module VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, instelling_id VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, waarde LONGTEXT NOT NULL, INDEX IDX_141F309D539B0606 (uid), PRIMARY KEY(uid, module, instelling_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE agenda (item_id INT AUTO_INCREMENT NOT NULL, titel VARCHAR(255) NOT NULL, beschrijving LONGTEXT DEFAULT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME NOT NULL, rechten_bekijken VARCHAR(255) NOT NULL, locatie VARCHAR(255) DEFAULT NULL, link VARCHAR(255) DEFAULT NULL, INDEX begin_moment (begin_moment), INDEX eind_moment (eind_moment), PRIMARY KEY(item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE agenda_verbergen (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, refuuid VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, PRIMARY KEY(uid, refuuid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE biebauteur (id INT AUTO_INCREMENT NOT NULL, auteur VARCHAR(100) DEFAULT \'\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE biebcategorie (id INT AUTO_INCREMENT NOT NULL, p_id INT DEFAULT NULL, categorie VARCHAR(255) NOT NULL, INDEX IDX_8FC553A3D37B63A2 (p_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE biebbeschrijving (id INT AUTO_INCREMENT NOT NULL, boek_id INT DEFAULT 0 NOT NULL, schrijver_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, beschrijving LONGTEXT NOT NULL, toegevoegd DATETIME NOT NULL, bewerkdatum DATETIME NOT NULL, INDEX IDX_38C7823495E149D3 (schrijver_uid), INDEX IDX_38C782345C12AB20 (boek_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE changelog (id INT AUTO_INCREMENT NOT NULL, moment DATETIME NOT NULL, subject VARCHAR(255) NOT NULL, property VARCHAR(255) NOT NULL, old_value LONGTEXT DEFAULT NULL, new_value LONGTEXT DEFAULT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE cms_paginas (naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, titel VARCHAR(255) NOT NULL, inhoud LONGTEXT NOT NULL, laatst_gewijzigd DATETIME NOT NULL, rechten_bekijken VARCHAR(255) NOT NULL, rechten_bewerken VARCHAR(255) NOT NULL, inline_html TINYINT(1) NOT NULL, PRIMARY KEY(naam)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE voorkeurCommissie (id INT AUTO_INCREMENT NOT NULL, categorie_id INT DEFAULT 1 NOT NULL, naam VARCHAR(255) NOT NULL, zichtbaar TINYINT(1) NOT NULL, INDEX IDX_6567316BCF5E72D (categorie_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE voorkeurCommissieCategorie (id INT AUTO_INCREMENT NOT NULL, naam VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE voorkeurOpmerking (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, lidOpmerking LONGTEXT DEFAULT NULL, praesesOpmerking LONGTEXT DEFAULT NULL, PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE voorkeurVoorkeur (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, cid INT NOT NULL, voorkeur INT NOT NULL, timestamp DATETIME NOT NULL, INDEX IDX_1A129E32539B0606 (uid), INDEX IDX_1A129E324B30D9C4 (cid), PRIMARY KEY(uid, cid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE crv_kwalificaties (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, functie_id INT NOT NULL, wanneer_toegewezen DATETIME NOT NULL, INDEX IDX_A7837604539B0606 (uid), INDEX IDX_A78376046B113FD2 (functie_id), PRIMARY KEY(uid, functie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE crv_voorkeuren (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, crv_repetitie_id INT NOT NULL, INDEX IDX_5BDAE73AC0ADB06C (crv_repetitie_id), INDEX IDX_5BDAE73A539B0606 (uid), PRIMARY KEY(uid, crv_repetitie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE crv_vrijstellingen (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, begin_datum DATETIME NOT NULL, eind_datum DATETIME NOT NULL, percentage INT NOT NULL, PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE courant (id INT AUTO_INCREMENT NOT NULL, verzender VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, verzendMoment DATETIME NOT NULL, inhoud LONGTEXT NOT NULL, INDEX IDX_CB97613A4F817B88 (verzender), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE courantbericht (id INT AUTO_INCREMENT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, titel VARCHAR(255) NOT NULL, cat ENUM(\'voorwoord\', \'bestuur\', \'csr\', \'overig\', \'sponsor\') COMMENT \'(DC2Type:enumCourantCategorie)\' NOT NULL COMMENT \'(DC2Type:enumCourantCategorie)\', bericht LONGTEXT NOT NULL, volgorde INT NOT NULL, datumTijd DATETIME NOT NULL, INDEX IDX_A14C826A539B0606 (uid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE debug_log (id INT AUTO_INCREMENT NOT NULL, class_function VARCHAR(255) NOT NULL, dump LONGTEXT COMMENT \'(DC2Type:longtext)\' NOT NULL, call_trace LONGTEXT NOT NULL, moment DATETIME NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' DEFAULT NULL, su_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' DEFAULT NULL, ip VARCHAR(255) NOT NULL, request VARCHAR(255) NOT NULL, referer VARCHAR(255) DEFAULT NULL, user_agent VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE Document (id INT AUTO_INCREMENT NOT NULL, categorie_id INT NOT NULL, eigenaar VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, naam VARCHAR(255) NOT NULL, toegevoegd DATETIME NOT NULL, leesrechten VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, filesize INT NOT NULL, mimetype VARCHAR(255) NOT NULL, INDEX IDX_211FE820BCF5E72D (categorie_id), INDEX IDX_211FE820F725D48E (eigenaar), INDEX Zoeken (naam, filename), INDEX toegevoegd (toegevoegd), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE DocumentCategorie (id INT AUTO_INCREMENT NOT NULL, naam VARCHAR(255) NOT NULL, zichtbaar TINYINT(1) NOT NULL, leesrechten VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE eetplan (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, woonoord_id INT NOT NULL, avond DATE DEFAULT NULL, opmerking VARCHAR(255) DEFAULT NULL, INDEX IDX_EC97E0BBF0C31BC7 (woonoord_id), INDEX IDX_EC97E0BB539B0606 (uid), PRIMARY KEY(uid, woonoord_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE eetplan_bekenden (uid1 VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, uid2 VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, INDEX IDX_17EC81326AECD184 (uid1), INDEX IDX_17EC8132F3E5803E (uid2), PRIMARY KEY(uid1, uid2)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE forum_categorien (categorie_id INT AUTO_INCREMENT NOT NULL, titel VARCHAR(255) NOT NULL, rechten_lezen VARCHAR(255) NOT NULL, volgorde INT NOT NULL, INDEX volgorde (volgorde), PRIMARY KEY(categorie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE forum_delen (forum_id INT AUTO_INCREMENT NOT NULL, categorie_id INT NOT NULL, titel VARCHAR(255) NOT NULL, omschrijving LONGTEXT NOT NULL, rechten_lezen VARCHAR(255) NOT NULL, rechten_posten VARCHAR(255) NOT NULL, rechten_modereren VARCHAR(255) NOT NULL, volgorde INT NOT NULL, INDEX IDX_4D51668FBCF5E72D (categorie_id), INDEX volgorde (volgorde), PRIMARY KEY(forum_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE forum_delen_meldingen (forum_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, INDEX IDX_7525C01529CCBAD0 (forum_id), PRIMARY KEY(forum_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE forum_draden (draad_id INT AUTO_INCREMENT NOT NULL, forum_id INT NOT NULL, gedeeld_met INT DEFAULT NULL, laatste_post_id INT DEFAULT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, titel VARCHAR(255) NOT NULL, datum_tijd DATETIME NOT NULL, laatst_gewijzigd DATETIME DEFAULT NULL, laatste_wijziging_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' DEFAULT NULL, gesloten TINYINT(1) NOT NULL, verwijderd TINYINT(1) NOT NULL, wacht_goedkeuring TINYINT(1) NOT NULL, plakkerig TINYINT(1) NOT NULL, belangrijk VARCHAR(255) DEFAULT NULL, eerste_post_plakkerig TINYINT(1) NOT NULL, pagina_per_post TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_C7DE4CB6E196D02C (laatste_post_id), INDEX IDX_C7DE4CB629CCBAD0 (forum_id), INDEX IDX_C7DE4CB6EAAB93BA (gedeeld_met), INDEX verwijderd (verwijderd), INDEX plakkerig (plakkerig), INDEX belangrijk (belangrijk), INDEX laatst_gewijzigd (laatst_gewijzigd), INDEX titel (titel), INDEX wacht_goedkeuring (wacht_goedkeuring), PRIMARY KEY(draad_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE forum_draden_gelezen (draad_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, datum_tijd DATETIME NOT NULL, INDEX IDX_A4E3F87E539B0606 (uid), INDEX IDX_A4E3F87ECA4E5E (draad_id), PRIMARY KEY(draad_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE forum_draden_volgen (draad_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, niveau ENUM(\'nooit\', \'vermelding\', \'altijd\') COMMENT \'(DC2Type:enumForumDraadMeldingNiveau)\' NOT NULL COMMENT \'(DC2Type:enumForumDraadMeldingNiveau)\', INDEX IDX_E660A9C9CA4E5E (draad_id), PRIMARY KEY(draad_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE forum_draden_reageren (forum_id INT NOT NULL, draad_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, datum_tijd DATETIME NOT NULL, concept LONGTEXT DEFAULT NULL, titel VARCHAR(255) DEFAULT NULL, PRIMARY KEY(forum_id, draad_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE forum_draden_verbergen (draad_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, INDEX IDX_40739E14CA4E5E (draad_id), PRIMARY KEY(draad_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE forum_posts (post_id INT AUTO_INCREMENT NOT NULL, draad_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, tekst LONGTEXT NOT NULL, datum_tijd DATETIME NOT NULL, laatst_gewijzigd DATETIME NOT NULL, bewerkt_tekst LONGTEXT DEFAULT NULL, verwijderd TINYINT(1) NOT NULL, auteur_ip VARCHAR(255) NOT NULL, wacht_goedkeuring TINYINT(1) NOT NULL, INDEX IDX_90291C2DCA4E5E (draad_id), INDEX verwijderd (verwijderd), FULLTEXT INDEX tekst (tekst), INDEX lid_id (uid), INDEX datum_tijd (datum_tijd), INDEX wacht_goedkeuring (wacht_goedkeuring), PRIMARY KEY(post_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE forumplaatjes (id INT AUTO_INCREMENT NOT NULL, maker VARCHAR(4) COMMENT \'(DC2Type:uid)\' DEFAULT NULL, access_key VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, datum_toegevoegd DATETIME NOT NULL, source_url LONGTEXT DEFAULT NULL, INDEX IDX_1781803FC6197FB4 (maker), INDEX access_key (access_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE fotos (subdir VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, filename VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, owner VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, rotation INT NOT NULL, INDEX IDX_CB8405C7CF60E67C (owner), PRIMARY KEY(subdir, filename)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE fotoalbums (subdir VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, owner VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, INDEX IDX_AC6D17BECF60E67C (owner), PRIMARY KEY(subdir)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE foto_tags (refuuid VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, keyword VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, door VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, wanneer DATETIME NOT NULL, x DOUBLE PRECISION NOT NULL, y DOUBLE PRECISION NOT NULL, size DOUBLE PRECISION NOT NULL, PRIMARY KEY(refuuid, keyword)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE GoogleToken (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, token VARCHAR(255) NOT NULL, PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE activiteiten (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, aanmeld_limiet INT DEFAULT NULL, aanmelden_vanaf DATETIME NOT NULL, aanmelden_tot DATETIME NOT NULL, bewerken_tot DATETIME DEFAULT NULL, afmelden_tot DATETIME DEFAULT NULL, soort VARCHAR(255) NOT NULL, rechten_aanmelden VARCHAR(255) DEFAULT NULL, locatie VARCHAR(255) DEFAULT NULL, in_agenda TINYINT(1) NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' NOT NULL COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT NOT NULL, omschrijving LONGTEXT DEFAULT NULL, keuzelijst VARCHAR(255) DEFAULT NULL, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' NOT NULL COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' DEFAULT NULL, INDEX IDX_1C50895F3A4A27C1 (maker_uid), INDEX begin_moment (begin_moment), INDEX soort (soort), INDEX familie (familie), INDEX in_agenda (in_agenda), INDEX status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE activiteit_deelnemers (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' DEFAULT NULL, lid_sinds DATETIME NOT NULL, INDEX IDX_7F206BAB9EB44EC5 (groep_id), INDEX IDX_7F206BAB539B0606 (uid), INDEX IDX_7F206BAB97983E4 (door_uid), INDEX lid_sinds (lid_sinds), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE besturen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, bijbeltekst LONGTEXT NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' NOT NULL COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT NOT NULL, omschrijving LONGTEXT DEFAULT NULL, keuzelijst VARCHAR(255) DEFAULT NULL, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' NOT NULL COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' DEFAULT NULL, INDEX IDX_16921DA03A4A27C1 (maker_uid), INDEX status (status), INDEX begin_moment (begin_moment), INDEX familie (familie), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE bestuurs_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' DEFAULT NULL, lid_sinds DATETIME NOT NULL, INDEX IDX_7BE62A789EB44EC5 (groep_id), INDEX IDX_7BE62A78539B0606 (uid), INDEX IDX_7BE62A7897983E4 (door_uid), INDEX lid_sinds (lid_sinds), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE commissies (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, soort VARCHAR(255) NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' NOT NULL COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT NOT NULL, omschrijving LONGTEXT DEFAULT NULL, keuzelijst VARCHAR(255) DEFAULT NULL, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' NOT NULL COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' DEFAULT NULL, INDEX IDX_858C850B3A4A27C1 (maker_uid), INDEX status (status), INDEX begin_moment (begin_moment), INDEX soort (soort), INDEX familie (familie), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE commissie_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' DEFAULT NULL, lid_sinds DATETIME NOT NULL, INDEX IDX_18A4E69E9EB44EC5 (groep_id), INDEX IDX_18A4E69E539B0606 (uid), INDEX IDX_18A4E69E97983E4 (door_uid), INDEX lid_sinds (lid_sinds), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE ketzers (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, aanmeld_limiet INT DEFAULT NULL, aanmelden_vanaf DATETIME NOT NULL, aanmelden_tot DATETIME NOT NULL, bewerken_tot DATETIME DEFAULT NULL, afmelden_tot DATETIME DEFAULT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' NOT NULL COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT NOT NULL, omschrijving LONGTEXT DEFAULT NULL, keuzelijst VARCHAR(255) DEFAULT NULL, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' NOT NULL COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' DEFAULT NULL, INDEX IDX_DE2D6D463A4A27C1 (maker_uid), INDEX status (status), INDEX begin_moment (begin_moment), INDEX familie (familie), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE ketzer_deelnemers (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' DEFAULT NULL, lid_sinds DATETIME NOT NULL, INDEX IDX_E29708B29EB44EC5 (groep_id), INDEX IDX_E29708B2539B0606 (uid), INDEX IDX_E29708B297983E4 (door_uid), INDEX lid_sinds (lid_sinds), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE kringen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, verticale CHAR(1) NOT NULL, kring_nummer INT NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' NOT NULL COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT NOT NULL, omschrijving LONGTEXT DEFAULT NULL, keuzelijst VARCHAR(255) DEFAULT NULL, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' NOT NULL COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' DEFAULT NULL, INDEX IDX_E2F4F0BF3A4A27C1 (maker_uid), INDEX begin_moment (begin_moment), INDEX kring_nummer (kring_nummer), INDEX familie (familie), INDEX verticale (verticale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE kring_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' DEFAULT NULL, lid_sinds DATETIME NOT NULL, INDEX IDX_C1C295369EB44EC5 (groep_id), INDEX IDX_C1C29536539B0606 (uid), INDEX IDX_C1C2953697983E4 (door_uid), INDEX lid_sinds (lid_sinds), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE lichtingen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, lidjaar INT NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' NOT NULL COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT NOT NULL, omschrijving LONGTEXT DEFAULT NULL, keuzelijst VARCHAR(255) DEFAULT NULL, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' NOT NULL COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' DEFAULT NULL, UNIQUE INDEX UNIQ_1EDCCA6E4D508A76 (lidjaar), INDEX IDX_1EDCCA6E3A4A27C1 (maker_uid), INDEX begin_moment (begin_moment), INDEX familie (familie), INDEX status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE lichting_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' DEFAULT NULL, lid_sinds DATETIME NOT NULL, INDEX IDX_9F803B119EB44EC5 (groep_id), INDEX IDX_9F803B11539B0606 (uid), INDEX IDX_9F803B1197983E4 (door_uid), INDEX lid_sinds (lid_sinds), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE onderverenigingen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, soort VARCHAR(255) NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' NOT NULL COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT NOT NULL, omschrijving LONGTEXT DEFAULT NULL, keuzelijst VARCHAR(255) DEFAULT NULL, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' NOT NULL COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' DEFAULT NULL, INDEX IDX_F1E76283A4A27C1 (maker_uid), INDEX begin_moment (begin_moment), INDEX status (status), INDEX familie (familie), INDEX soort (soort), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE ondervereniging_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' DEFAULT NULL, lid_sinds DATETIME NOT NULL, INDEX IDX_7EC7AEBA9EB44EC5 (groep_id), INDEX IDX_7EC7AEBA539B0606 (uid), INDEX IDX_7EC7AEBA97983E4 (door_uid), INDEX lid_sinds (lid_sinds), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE groepen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, rechten_aanmelden VARCHAR(255) NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' NOT NULL COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT NOT NULL, omschrijving LONGTEXT DEFAULT NULL, keuzelijst VARCHAR(255) DEFAULT NULL, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' NOT NULL COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' DEFAULT NULL, INDEX IDX_647C5D9F3A4A27C1 (maker_uid), INDEX begin_moment (begin_moment), INDEX familie (familie), INDEX status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE groep_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' DEFAULT NULL, lid_sinds DATETIME NOT NULL, INDEX IDX_47D1C06D9EB44EC5 (groep_id), INDEX IDX_47D1C06D539B0606 (uid), INDEX IDX_47D1C06D97983E4 (door_uid), INDEX lid_sinds (lid_sinds), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE verticalen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, letter CHAR(1) NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' NOT NULL COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT NOT NULL, omschrijving LONGTEXT DEFAULT NULL, keuzelijst VARCHAR(255) DEFAULT NULL, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' NOT NULL COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' DEFAULT NULL, UNIQUE INDEX UNIQ_79C519078E02EE0A (letter), UNIQUE INDEX UNIQ_79C51907FC4DB938 (naam), INDEX IDX_79C519073A4A27C1 (maker_uid), INDEX begin_moment (begin_moment), INDEX familie (familie), INDEX status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE verticale_leden (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' DEFAULT NULL, lid_sinds DATETIME NOT NULL, INDEX IDX_52C85C389EB44EC5 (groep_id), INDEX IDX_52C85C38539B0606 (uid), INDEX IDX_52C85C3897983E4 (door_uid), INDEX lid_sinds (lid_sinds), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE werkgroepen (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, aanmeld_limiet INT DEFAULT NULL, aanmelden_vanaf DATETIME NOT NULL, aanmelden_tot DATETIME NOT NULL, bewerken_tot DATETIME DEFAULT NULL, afmelden_tot DATETIME DEFAULT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' NOT NULL COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT NOT NULL, omschrijving LONGTEXT DEFAULT NULL, keuzelijst VARCHAR(255) DEFAULT NULL, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' NOT NULL COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' DEFAULT NULL, INDEX IDX_2194ECF73A4A27C1 (maker_uid), INDEX begin_moment (begin_moment), INDEX familie (familie), INDEX status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE werkgroep_deelnemers (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' DEFAULT NULL, lid_sinds DATETIME NOT NULL, INDEX IDX_38E14A6B9EB44EC5 (groep_id), INDEX IDX_38E14A6B539B0606 (uid), INDEX IDX_38E14A6B97983E4 (door_uid), INDEX lid_sinds (lid_sinds), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE woonoorden (id INT AUTO_INCREMENT NOT NULL, maker_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, soort ENUM(\'w\', \'h\') COMMENT \'(DC2Type:enumHuisStatus)\' NOT NULL COMMENT \'(DC2Type:enumHuisStatus)\', eetplan TINYINT(1) NOT NULL, naam VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, familie VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, begin_moment DATETIME NOT NULL, eind_moment DATETIME DEFAULT NULL, status ENUM(\'ft\', \'ht\', \'ot\') COMMENT \'(DC2Type:enumGroepStatus)\' NOT NULL COMMENT \'(DC2Type:enumGroepStatus)\', samenvatting LONGTEXT NOT NULL, omschrijving LONGTEXT DEFAULT NULL, keuzelijst VARCHAR(255) DEFAULT NULL, versie ENUM(\'v1\', \'v2\') COMMENT \'(DC2Type:enumGroepVersie)\' NOT NULL COMMENT \'(DC2Type:enumGroepVersie)\', keuzelijst2 TEXT COMMENT \'(DC2Type:groepkeuze)\' DEFAULT NULL, INDEX IDX_782FB8083A4A27C1 (maker_uid), INDEX familie (familie), INDEX status (status), INDEX begin_moment (begin_moment), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE bewoners (groep_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, opmerking VARCHAR(255) DEFAULT NULL, opmerking2 TEXT COMMENT \'(DC2Type:groepkeuzeselectie)\' DEFAULT NULL, lid_sinds DATETIME NOT NULL, INDEX IDX_62C774019EB44EC5 (groep_id), INDEX IDX_62C77401539B0606 (uid), INDEX IDX_62C7740197983E4 (door_uid), INDEX lid_sinds (lid_sinds), PRIMARY KEY(groep_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE instellingen (module VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, instelling_id VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, waarde LONGTEXT NOT NULL, PRIMARY KEY(module, instelling_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE lidinstellingen (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, module VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, instelling_id VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, waarde LONGTEXT NOT NULL, INDEX IDX_2059B4DF539B0606 (uid), PRIMARY KEY(uid, module, instelling_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE memory_scores (id INT AUTO_INCREMENT NOT NULL, tijd INT NOT NULL, beurten INT NOT NULL, goed INT NOT NULL, groep VARCHAR(255) NOT NULL, eerlijk TINYINT(1) NOT NULL, door_uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, wanneer DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE log (ID INT AUTO_INCREMENT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, ip VARCHAR(255) NOT NULL, locatie VARCHAR(255) NOT NULL, moment DATETIME NOT NULL, url VARCHAR(255) NOT NULL, referer VARCHAR(255) NOT NULL, useragent VARCHAR(255) NOT NULL, INDEX uid (uid), INDEX moment (moment), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE mlt_beoordelingen (maaltijd_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, kwantiteit DOUBLE PRECISION DEFAULT NULL, kwaliteit DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(maaltijd_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE menus (item_id INT AUTO_INCREMENT NOT NULL, parent_id INT NOT NULL, volgorde INT NOT NULL, tekst VARCHAR(255) NOT NULL, link VARCHAR(255) NOT NULL, rechten_bekijken VARCHAR(255) DEFAULT NULL, zichtbaar TINYINT(1) NOT NULL, INDEX IDX_727508CF727ACA70 (parent_id), INDEX prioriteit (volgorde), PRIMARY KEY(item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE peiling (id INT AUTO_INCREMENT NOT NULL, eigenaar VARCHAR(4) COMMENT \'(DC2Type:uid)\' DEFAULT NULL, titel VARCHAR(255) NOT NULL, beschrijving LONGTEXT NOT NULL, mag_bewerken TINYINT(1) DEFAULT \'0\' NOT NULL, resultaat_zichtbaar TINYINT(1) DEFAULT \'1\' NOT NULL, aantal_voorstellen INT DEFAULT 0 NOT NULL, aantal_stemmen INT DEFAULT 1 NOT NULL, rechten_stemmen VARCHAR(255) DEFAULT NULL, rechten_mod VARCHAR(255) DEFAULT NULL, sluitingsdatum DATETIME DEFAULT NULL, INDEX IDX_A3418E46F725D48E (eigenaar), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE peiling_optie (id INT AUTO_INCREMENT NOT NULL, peiling_id INT NOT NULL, titel VARCHAR(255) NOT NULL, beschrijving LONGTEXT DEFAULT NULL, stemmen INT NOT NULL, ingebracht_door VARCHAR(4) COMMENT \'(DC2Type:uid)\' DEFAULT NULL, INDEX IDX_C919E5D7B68DF022 (peiling_id), INDEX optie (titel), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE peiling_stemmen (peiling_id INT NOT NULL, uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, aantal INT DEFAULT 1 NOT NULL, INDEX IDX_A5E8105539B0606 (uid), INDEX IDX_A5E8105B68DF022 (peiling_id), PRIMARY KEY(peiling_id, uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE pin_transacties (id INT AUTO_INCREMENT NOT NULL, datetime DATETIME NOT NULL, brand VARCHAR(255) NOT NULL, merchant VARCHAR(255) NOT NULL, store VARCHAR(255) NOT NULL, terminal VARCHAR(255) NOT NULL, tid VARCHAR(255) NOT NULL, mid VARCHAR(255) NOT NULL, ref VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, amount VARCHAR(255) NOT NULL, autrsp VARCHAR(255) NOT NULL, stan VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE pin_transactie_match (id INT AUTO_INCREMENT NOT NULL, transactie_id INT DEFAULT NULL, bestelling_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, notitie TEXT DEFAULT NULL, INDEX IDX_457B997D1D647A75 (transactie_id), INDEX IDX_457B997DA2E63037 (bestelling_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE savedquery (id INT AUTO_INCREMENT NOT NULL, savedquery LONGTEXT NOT NULL, beschrijving VARCHAR(255) NOT NULL, permissie VARCHAR(255) DEFAULT \'P_LOGGED_IN\' NOT NULL, categorie VARCHAR(255) DEFAULT \'Overig\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE acl (environment VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, action VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, resource VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, subject VARCHAR(255) NOT NULL, PRIMARY KEY(environment, action, resource)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('CREATE TABLE onetime_tokens (uid VARCHAR(4) COMMENT \'(DC2Type:uid)\' NOT NULL, url VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, token VARCHAR(191) COMMENT \'(DC2Type:stringkey)\' NOT NULL, expire DATETIME NOT NULL, verified TINYINT(1) NOT NULL, PRIMARY KEY(uid, url)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
		$this->addSql('ALTER TABLE login_sessions ADD CONSTRAINT FK_B4C4BD8C539B0606 FOREIGN KEY (uid) REFERENCES accounts (uid)');
		$this->addSql('ALTER TABLE accounts ADD CONSTRAINT FK_CAC89EAC539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE login_remember ADD CONSTRAINT FK_BD5B5182539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE profielen ADD CONSTRAINT FK_301B6229742C4A98 FOREIGN KEY (patroon) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE mlt_aanmeldingen ADD CONSTRAINT FK_B156D32F539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE mlt_aanmeldingen ADD CONSTRAINT FK_B156D32FCBA49CBE FOREIGN KEY (maaltijd_id) REFERENCES mlt_maaltijden (maaltijd_id)');
		$this->addSql('ALTER TABLE mlt_aanmeldingen ADD CONSTRAINT FK_B156D32F97983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE mlt_aanmeldingen ADD CONSTRAINT FK_B156D32F19F42197 FOREIGN KEY (door_abonnement) REFERENCES mlt_repetities (mlt_repetitie_id)');
		$this->addSql('ALTER TABLE mlt_maaltijden ADD CONSTRAINT FK_20DD1727A8500550 FOREIGN KEY (mlt_repetitie_id) REFERENCES mlt_repetities (mlt_repetitie_id)');
		$this->addSql('ALTER TABLE mlt_maaltijden ADD CONSTRAINT FK_20DD17274584665A FOREIGN KEY (product_id) REFERENCES CiviProduct (id)');
		$this->addSql('ALTER TABLE mlt_repetities ADD CONSTRAINT FK_5505370E4584665A FOREIGN KEY (product_id) REFERENCES CiviProduct (id)');
		$this->addSql('ALTER TABLE mlt_abonnementen ADD CONSTRAINT FK_CA961AB0A8500550 FOREIGN KEY (mlt_repetitie_id) REFERENCES mlt_repetities (mlt_repetitie_id)');
		$this->addSql('ALTER TABLE crv_taken ADD CONSTRAINT FK_66384104539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE crv_taken ADD CONSTRAINT FK_66384104C0ADB06C FOREIGN KEY (crv_repetitie_id) REFERENCES crv_repetities (crv_repetitie_id)');
		$this->addSql('ALTER TABLE crv_taken ADD CONSTRAINT FK_66384104CBA49CBE FOREIGN KEY (maaltijd_id) REFERENCES mlt_maaltijden (maaltijd_id)');
		$this->addSql('ALTER TABLE crv_taken ADD CONSTRAINT FK_663841046B113FD2 FOREIGN KEY (functie_id) REFERENCES crv_functies (functie_id)');
		$this->addSql('ALTER TABLE crv_repetities ADD CONSTRAINT FK_3C44567BA8500550 FOREIGN KEY (mlt_repetitie_id) REFERENCES mlt_repetities (mlt_repetitie_id)');
		$this->addSql('ALTER TABLE crv_repetities ADD CONSTRAINT FK_3C44567B6B113FD2 FOREIGN KEY (functie_id) REFERENCES crv_functies (functie_id)');
		$this->addSql('ALTER TABLE CiviProduct ADD CONSTRAINT FK_C4590238BCF5E72D FOREIGN KEY (categorie_id) REFERENCES CiviCategorie (id)');
		$this->addSql('ALTER TABLE CiviBestellingInhoud ADD CONSTRAINT FK_30A7C75CA2E63037 FOREIGN KEY (bestelling_id) REFERENCES CiviBestelling (id)');
		$this->addSql('ALTER TABLE CiviBestellingInhoud ADD CONSTRAINT FK_30A7C75C4584665A FOREIGN KEY (product_id) REFERENCES CiviProduct (id)');
		$this->addSql('ALTER TABLE CiviBestelling ADD CONSTRAINT FK_290D88AC539B0606 FOREIGN KEY (uid) REFERENCES CiviSaldo (uid)');
		$this->addSql('ALTER TABLE CiviPrijs ADD CONSTRAINT FK_86CCDFA74584665A FOREIGN KEY (product_id) REFERENCES CiviProduct (id)');
		$this->addSql('ALTER TABLE biebexemplaar ADD CONSTRAINT FK_27CEE3A452DCF440 FOREIGN KEY (eigenaar_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE biebexemplaar ADD CONSTRAINT FK_27CEE3A4C5564237 FOREIGN KEY (uitgeleend_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE biebexemplaar ADD CONSTRAINT FK_27CEE3A45C12AB20 FOREIGN KEY (boek_id) REFERENCES biebboek (id)');
		$this->addSql('ALTER TABLE biebboek ADD CONSTRAINT FK_42475FFA60BB6FE6 FOREIGN KEY (auteur_id) REFERENCES biebauteur (id)');
		$this->addSql('ALTER TABLE biebboek ADD CONSTRAINT FK_42475FFABCF5E72D FOREIGN KEY (categorie_id) REFERENCES biebcategorie (id)');
		$this->addSql('ALTER TABLE lidtoestemmingen ADD CONSTRAINT FK_141F309D539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE biebcategorie ADD CONSTRAINT FK_8FC553A3D37B63A2 FOREIGN KEY (p_id) REFERENCES biebcategorie (id)');
		$this->addSql('ALTER TABLE biebbeschrijving ADD CONSTRAINT FK_38C7823495E149D3 FOREIGN KEY (schrijver_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE biebbeschrijving ADD CONSTRAINT FK_38C782345C12AB20 FOREIGN KEY (boek_id) REFERENCES biebboek (id)');
		$this->addSql('ALTER TABLE voorkeurCommissie ADD CONSTRAINT FK_6567316BCF5E72D FOREIGN KEY (categorie_id) REFERENCES voorkeurCommissieCategorie (id)');
		$this->addSql('ALTER TABLE voorkeurOpmerking ADD CONSTRAINT FK_9BC92946539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE voorkeurVoorkeur ADD CONSTRAINT FK_1A129E32539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE voorkeurVoorkeur ADD CONSTRAINT FK_1A129E324B30D9C4 FOREIGN KEY (cid) REFERENCES voorkeurCommissie (id)');
		$this->addSql('ALTER TABLE crv_kwalificaties ADD CONSTRAINT FK_A7837604539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE crv_kwalificaties ADD CONSTRAINT FK_A78376046B113FD2 FOREIGN KEY (functie_id) REFERENCES crv_functies (functie_id)');
		$this->addSql('ALTER TABLE crv_voorkeuren ADD CONSTRAINT FK_5BDAE73AC0ADB06C FOREIGN KEY (crv_repetitie_id) REFERENCES crv_repetities (crv_repetitie_id)');
		$this->addSql('ALTER TABLE crv_voorkeuren ADD CONSTRAINT FK_5BDAE73A539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE crv_vrijstellingen ADD CONSTRAINT FK_E864A0B9539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE courant ADD CONSTRAINT FK_CB97613A4F817B88 FOREIGN KEY (verzender) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE courantbericht ADD CONSTRAINT FK_A14C826A539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE Document ADD CONSTRAINT FK_211FE820BCF5E72D FOREIGN KEY (categorie_id) REFERENCES DocumentCategorie (id)');
		$this->addSql('ALTER TABLE Document ADD CONSTRAINT FK_211FE820F725D48E FOREIGN KEY (eigenaar) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE eetplan ADD CONSTRAINT FK_EC97E0BBF0C31BC7 FOREIGN KEY (woonoord_id) REFERENCES woonoorden (id)');
		$this->addSql('ALTER TABLE eetplan ADD CONSTRAINT FK_EC97E0BB539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE eetplan_bekenden ADD CONSTRAINT FK_17EC81326AECD184 FOREIGN KEY (uid1) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE eetplan_bekenden ADD CONSTRAINT FK_17EC8132F3E5803E FOREIGN KEY (uid2) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE forum_delen ADD CONSTRAINT FK_4D51668FBCF5E72D FOREIGN KEY (categorie_id) REFERENCES forum_categorien (categorie_id)');
		$this->addSql('ALTER TABLE forum_delen_meldingen ADD CONSTRAINT FK_7525C01529CCBAD0 FOREIGN KEY (forum_id) REFERENCES forum_delen (forum_id)');
		$this->addSql('ALTER TABLE forum_draden ADD CONSTRAINT FK_C7DE4CB6E196D02C FOREIGN KEY (laatste_post_id) REFERENCES forum_posts (post_id)');
		$this->addSql('ALTER TABLE forum_draden ADD CONSTRAINT FK_C7DE4CB629CCBAD0 FOREIGN KEY (forum_id) REFERENCES forum_delen (forum_id)');
		$this->addSql('ALTER TABLE forum_draden ADD CONSTRAINT FK_C7DE4CB6EAAB93BA FOREIGN KEY (gedeeld_met) REFERENCES forum_delen (forum_id)');
		$this->addSql('ALTER TABLE forum_draden_gelezen ADD CONSTRAINT FK_A4E3F87E539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE forum_draden_gelezen ADD CONSTRAINT FK_A4E3F87ECA4E5E FOREIGN KEY (draad_id) REFERENCES forum_draden (draad_id)');
		$this->addSql('ALTER TABLE forum_draden_volgen ADD CONSTRAINT FK_E660A9C9CA4E5E FOREIGN KEY (draad_id) REFERENCES forum_draden (draad_id)');
		$this->addSql('ALTER TABLE forum_draden_verbergen ADD CONSTRAINT FK_40739E14CA4E5E FOREIGN KEY (draad_id) REFERENCES forum_draden (draad_id)');
		$this->addSql('ALTER TABLE forum_posts ADD CONSTRAINT FK_90291C2DCA4E5E FOREIGN KEY (draad_id) REFERENCES forum_draden (draad_id)');
		$this->addSql('ALTER TABLE forumplaatjes ADD CONSTRAINT FK_1781803FC6197FB4 FOREIGN KEY (maker) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE fotos ADD CONSTRAINT FK_CB8405C7CF60E67C FOREIGN KEY (owner) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE fotoalbums ADD CONSTRAINT FK_AC6D17BECF60E67C FOREIGN KEY (owner) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE activiteiten ADD CONSTRAINT FK_1C50895F3A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE activiteit_deelnemers ADD CONSTRAINT FK_7F206BAB9EB44EC5 FOREIGN KEY (groep_id) REFERENCES activiteiten (id)');
		$this->addSql('ALTER TABLE activiteit_deelnemers ADD CONSTRAINT FK_7F206BAB539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE activiteit_deelnemers ADD CONSTRAINT FK_7F206BAB97983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE besturen ADD CONSTRAINT FK_16921DA03A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE bestuurs_leden ADD CONSTRAINT FK_7BE62A789EB44EC5 FOREIGN KEY (groep_id) REFERENCES besturen (id)');
		$this->addSql('ALTER TABLE bestuurs_leden ADD CONSTRAINT FK_7BE62A78539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE bestuurs_leden ADD CONSTRAINT FK_7BE62A7897983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE commissies ADD CONSTRAINT FK_858C850B3A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE commissie_leden ADD CONSTRAINT FK_18A4E69E9EB44EC5 FOREIGN KEY (groep_id) REFERENCES commissies (id)');
		$this->addSql('ALTER TABLE commissie_leden ADD CONSTRAINT FK_18A4E69E539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE commissie_leden ADD CONSTRAINT FK_18A4E69E97983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE ketzers ADD CONSTRAINT FK_DE2D6D463A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE ketzer_deelnemers ADD CONSTRAINT FK_E29708B29EB44EC5 FOREIGN KEY (groep_id) REFERENCES ketzers (id)');
		$this->addSql('ALTER TABLE ketzer_deelnemers ADD CONSTRAINT FK_E29708B2539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE ketzer_deelnemers ADD CONSTRAINT FK_E29708B297983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE kringen ADD CONSTRAINT FK_E2F4F0BF3A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE kring_leden ADD CONSTRAINT FK_C1C295369EB44EC5 FOREIGN KEY (groep_id) REFERENCES kringen (id)');
		$this->addSql('ALTER TABLE kring_leden ADD CONSTRAINT FK_C1C29536539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE kring_leden ADD CONSTRAINT FK_C1C2953697983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE lichtingen ADD CONSTRAINT FK_1EDCCA6E3A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE lichting_leden ADD CONSTRAINT FK_9F803B119EB44EC5 FOREIGN KEY (groep_id) REFERENCES lichtingen (id)');
		$this->addSql('ALTER TABLE lichting_leden ADD CONSTRAINT FK_9F803B11539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE lichting_leden ADD CONSTRAINT FK_9F803B1197983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE onderverenigingen ADD CONSTRAINT FK_F1E76283A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE ondervereniging_leden ADD CONSTRAINT FK_7EC7AEBA9EB44EC5 FOREIGN KEY (groep_id) REFERENCES onderverenigingen (id)');
		$this->addSql('ALTER TABLE ondervereniging_leden ADD CONSTRAINT FK_7EC7AEBA539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE ondervereniging_leden ADD CONSTRAINT FK_7EC7AEBA97983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE groepen ADD CONSTRAINT FK_647C5D9F3A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE groep_leden ADD CONSTRAINT FK_47D1C06D9EB44EC5 FOREIGN KEY (groep_id) REFERENCES groepen (id)');
		$this->addSql('ALTER TABLE groep_leden ADD CONSTRAINT FK_47D1C06D539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE groep_leden ADD CONSTRAINT FK_47D1C06D97983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE verticalen ADD CONSTRAINT FK_79C519073A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE verticale_leden ADD CONSTRAINT FK_52C85C389EB44EC5 FOREIGN KEY (groep_id) REFERENCES verticalen (id)');
		$this->addSql('ALTER TABLE verticale_leden ADD CONSTRAINT FK_52C85C38539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE verticale_leden ADD CONSTRAINT FK_52C85C3897983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE werkgroepen ADD CONSTRAINT FK_2194ECF73A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE werkgroep_deelnemers ADD CONSTRAINT FK_38E14A6B9EB44EC5 FOREIGN KEY (groep_id) REFERENCES werkgroepen (id)');
		$this->addSql('ALTER TABLE werkgroep_deelnemers ADD CONSTRAINT FK_38E14A6B539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE werkgroep_deelnemers ADD CONSTRAINT FK_38E14A6B97983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE woonoorden ADD CONSTRAINT FK_782FB8083A4A27C1 FOREIGN KEY (maker_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE bewoners ADD CONSTRAINT FK_62C774019EB44EC5 FOREIGN KEY (groep_id) REFERENCES woonoorden (id)');
		$this->addSql('ALTER TABLE bewoners ADD CONSTRAINT FK_62C77401539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE bewoners ADD CONSTRAINT FK_62C7740197983E4 FOREIGN KEY (door_uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE lidinstellingen ADD CONSTRAINT FK_2059B4DF539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE menus ADD CONSTRAINT FK_727508CF727ACA70 FOREIGN KEY (parent_id) REFERENCES menus (item_id)');
		$this->addSql('ALTER TABLE peiling ADD CONSTRAINT FK_A3418E46F725D48E FOREIGN KEY (eigenaar) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE peiling_optie ADD CONSTRAINT FK_C919E5D7B68DF022 FOREIGN KEY (peiling_id) REFERENCES peiling (id)');
		$this->addSql('ALTER TABLE peiling_stemmen ADD CONSTRAINT FK_A5E8105539B0606 FOREIGN KEY (uid) REFERENCES profielen (uid)');
		$this->addSql('ALTER TABLE peiling_stemmen ADD CONSTRAINT FK_A5E8105B68DF022 FOREIGN KEY (peiling_id) REFERENCES peiling (id)');
		$this->addSql('ALTER TABLE pin_transactie_match ADD CONSTRAINT FK_457B997D1D647A75 FOREIGN KEY (transactie_id) REFERENCES pin_transacties (id)');
		$this->addSql('ALTER TABLE pin_transactie_match ADD CONSTRAINT FK_457B997DA2E63037 FOREIGN KEY (bestelling_id) REFERENCES CiviBestelling (id)');
	}

	public function down(Schema $schema): void {
		$this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

		$this->addSql('ALTER TABLE login_sessions DROP FOREIGN KEY FK_B4C4BD8C539B0606');
		$this->addSql('ALTER TABLE accounts DROP FOREIGN KEY FK_CAC89EAC539B0606');
		$this->addSql('ALTER TABLE login_remember DROP FOREIGN KEY FK_BD5B5182539B0606');
		$this->addSql('ALTER TABLE profielen DROP FOREIGN KEY FK_301B6229742C4A98');
		$this->addSql('ALTER TABLE mlt_aanmeldingen DROP FOREIGN KEY FK_B156D32F539B0606');
		$this->addSql('ALTER TABLE mlt_aanmeldingen DROP FOREIGN KEY FK_B156D32F97983E4');
		$this->addSql('ALTER TABLE crv_taken DROP FOREIGN KEY FK_66384104539B0606');
		$this->addSql('ALTER TABLE biebexemplaar DROP FOREIGN KEY FK_27CEE3A452DCF440');
		$this->addSql('ALTER TABLE biebexemplaar DROP FOREIGN KEY FK_27CEE3A4C5564237');
		$this->addSql('ALTER TABLE lidtoestemmingen DROP FOREIGN KEY FK_141F309D539B0606');
		$this->addSql('ALTER TABLE biebbeschrijving DROP FOREIGN KEY FK_38C7823495E149D3');
		$this->addSql('ALTER TABLE voorkeurOpmerking DROP FOREIGN KEY FK_9BC92946539B0606');
		$this->addSql('ALTER TABLE voorkeurVoorkeur DROP FOREIGN KEY FK_1A129E32539B0606');
		$this->addSql('ALTER TABLE crv_kwalificaties DROP FOREIGN KEY FK_A7837604539B0606');
		$this->addSql('ALTER TABLE crv_voorkeuren DROP FOREIGN KEY FK_5BDAE73A539B0606');
		$this->addSql('ALTER TABLE crv_vrijstellingen DROP FOREIGN KEY FK_E864A0B9539B0606');
		$this->addSql('ALTER TABLE courant DROP FOREIGN KEY FK_CB97613A4F817B88');
		$this->addSql('ALTER TABLE courantbericht DROP FOREIGN KEY FK_A14C826A539B0606');
		$this->addSql('ALTER TABLE Document DROP FOREIGN KEY FK_211FE820F725D48E');
		$this->addSql('ALTER TABLE eetplan DROP FOREIGN KEY FK_EC97E0BB539B0606');
		$this->addSql('ALTER TABLE eetplan_bekenden DROP FOREIGN KEY FK_17EC81326AECD184');
		$this->addSql('ALTER TABLE eetplan_bekenden DROP FOREIGN KEY FK_17EC8132F3E5803E');
		$this->addSql('ALTER TABLE forum_draden_gelezen DROP FOREIGN KEY FK_A4E3F87E539B0606');
		$this->addSql('ALTER TABLE forumplaatjes DROP FOREIGN KEY FK_1781803FC6197FB4');
		$this->addSql('ALTER TABLE fotos DROP FOREIGN KEY FK_CB8405C7CF60E67C');
		$this->addSql('ALTER TABLE fotoalbums DROP FOREIGN KEY FK_AC6D17BECF60E67C');
		$this->addSql('ALTER TABLE activiteiten DROP FOREIGN KEY FK_1C50895F3A4A27C1');
		$this->addSql('ALTER TABLE activiteit_deelnemers DROP FOREIGN KEY FK_7F206BAB539B0606');
		$this->addSql('ALTER TABLE activiteit_deelnemers DROP FOREIGN KEY FK_7F206BAB97983E4');
		$this->addSql('ALTER TABLE besturen DROP FOREIGN KEY FK_16921DA03A4A27C1');
		$this->addSql('ALTER TABLE bestuurs_leden DROP FOREIGN KEY FK_7BE62A78539B0606');
		$this->addSql('ALTER TABLE bestuurs_leden DROP FOREIGN KEY FK_7BE62A7897983E4');
		$this->addSql('ALTER TABLE commissies DROP FOREIGN KEY FK_858C850B3A4A27C1');
		$this->addSql('ALTER TABLE commissie_leden DROP FOREIGN KEY FK_18A4E69E539B0606');
		$this->addSql('ALTER TABLE commissie_leden DROP FOREIGN KEY FK_18A4E69E97983E4');
		$this->addSql('ALTER TABLE ketzers DROP FOREIGN KEY FK_DE2D6D463A4A27C1');
		$this->addSql('ALTER TABLE ketzer_deelnemers DROP FOREIGN KEY FK_E29708B2539B0606');
		$this->addSql('ALTER TABLE ketzer_deelnemers DROP FOREIGN KEY FK_E29708B297983E4');
		$this->addSql('ALTER TABLE kringen DROP FOREIGN KEY FK_E2F4F0BF3A4A27C1');
		$this->addSql('ALTER TABLE kring_leden DROP FOREIGN KEY FK_C1C29536539B0606');
		$this->addSql('ALTER TABLE kring_leden DROP FOREIGN KEY FK_C1C2953697983E4');
		$this->addSql('ALTER TABLE lichtingen DROP FOREIGN KEY FK_1EDCCA6E3A4A27C1');
		$this->addSql('ALTER TABLE lichting_leden DROP FOREIGN KEY FK_9F803B11539B0606');
		$this->addSql('ALTER TABLE lichting_leden DROP FOREIGN KEY FK_9F803B1197983E4');
		$this->addSql('ALTER TABLE onderverenigingen DROP FOREIGN KEY FK_F1E76283A4A27C1');
		$this->addSql('ALTER TABLE ondervereniging_leden DROP FOREIGN KEY FK_7EC7AEBA539B0606');
		$this->addSql('ALTER TABLE ondervereniging_leden DROP FOREIGN KEY FK_7EC7AEBA97983E4');
		$this->addSql('ALTER TABLE groepen DROP FOREIGN KEY FK_647C5D9F3A4A27C1');
		$this->addSql('ALTER TABLE groep_leden DROP FOREIGN KEY FK_47D1C06D539B0606');
		$this->addSql('ALTER TABLE groep_leden DROP FOREIGN KEY FK_47D1C06D97983E4');
		$this->addSql('ALTER TABLE verticalen DROP FOREIGN KEY FK_79C519073A4A27C1');
		$this->addSql('ALTER TABLE verticale_leden DROP FOREIGN KEY FK_52C85C38539B0606');
		$this->addSql('ALTER TABLE verticale_leden DROP FOREIGN KEY FK_52C85C3897983E4');
		$this->addSql('ALTER TABLE werkgroepen DROP FOREIGN KEY FK_2194ECF73A4A27C1');
		$this->addSql('ALTER TABLE werkgroep_deelnemers DROP FOREIGN KEY FK_38E14A6B539B0606');
		$this->addSql('ALTER TABLE werkgroep_deelnemers DROP FOREIGN KEY FK_38E14A6B97983E4');
		$this->addSql('ALTER TABLE woonoorden DROP FOREIGN KEY FK_782FB8083A4A27C1');
		$this->addSql('ALTER TABLE bewoners DROP FOREIGN KEY FK_62C77401539B0606');
		$this->addSql('ALTER TABLE bewoners DROP FOREIGN KEY FK_62C7740197983E4');
		$this->addSql('ALTER TABLE lidinstellingen DROP FOREIGN KEY FK_2059B4DF539B0606');
		$this->addSql('ALTER TABLE peiling DROP FOREIGN KEY FK_A3418E46F725D48E');
		$this->addSql('ALTER TABLE peiling_stemmen DROP FOREIGN KEY FK_A5E8105539B0606');
		$this->addSql('ALTER TABLE CiviBestelling DROP FOREIGN KEY FK_290D88AC539B0606');
		$this->addSql('ALTER TABLE mlt_aanmeldingen DROP FOREIGN KEY FK_B156D32FCBA49CBE');
		$this->addSql('ALTER TABLE crv_taken DROP FOREIGN KEY FK_66384104CBA49CBE');
		$this->addSql('ALTER TABLE mlt_aanmeldingen DROP FOREIGN KEY FK_B156D32F19F42197');
		$this->addSql('ALTER TABLE mlt_maaltijden DROP FOREIGN KEY FK_20DD1727A8500550');
		$this->addSql('ALTER TABLE mlt_abonnementen DROP FOREIGN KEY FK_CA961AB0A8500550');
		$this->addSql('ALTER TABLE crv_repetities DROP FOREIGN KEY FK_3C44567BA8500550');
		$this->addSql('ALTER TABLE crv_taken DROP FOREIGN KEY FK_66384104C0ADB06C');
		$this->addSql('ALTER TABLE crv_voorkeuren DROP FOREIGN KEY FK_5BDAE73AC0ADB06C');
		$this->addSql('ALTER TABLE crv_taken DROP FOREIGN KEY FK_663841046B113FD2');
		$this->addSql('ALTER TABLE crv_repetities DROP FOREIGN KEY FK_3C44567B6B113FD2');
		$this->addSql('ALTER TABLE crv_kwalificaties DROP FOREIGN KEY FK_A78376046B113FD2');
		$this->addSql('ALTER TABLE mlt_maaltijden DROP FOREIGN KEY FK_20DD17274584665A');
		$this->addSql('ALTER TABLE mlt_repetities DROP FOREIGN KEY FK_5505370E4584665A');
		$this->addSql('ALTER TABLE CiviBestellingInhoud DROP FOREIGN KEY FK_30A7C75C4584665A');
		$this->addSql('ALTER TABLE CiviPrijs DROP FOREIGN KEY FK_86CCDFA74584665A');
		$this->addSql('ALTER TABLE CiviBestellingInhoud DROP FOREIGN KEY FK_30A7C75CA2E63037');
		$this->addSql('ALTER TABLE pin_transactie_match DROP FOREIGN KEY FK_457B997DA2E63037');
		$this->addSql('ALTER TABLE CiviProduct DROP FOREIGN KEY FK_C4590238BCF5E72D');
		$this->addSql('ALTER TABLE biebexemplaar DROP FOREIGN KEY FK_27CEE3A45C12AB20');
		$this->addSql('ALTER TABLE biebbeschrijving DROP FOREIGN KEY FK_38C782345C12AB20');
		$this->addSql('ALTER TABLE biebboek DROP FOREIGN KEY FK_42475FFA60BB6FE6');
		$this->addSql('ALTER TABLE biebboek DROP FOREIGN KEY FK_42475FFABCF5E72D');
		$this->addSql('ALTER TABLE biebcategorie DROP FOREIGN KEY FK_8FC553A3D37B63A2');
		$this->addSql('ALTER TABLE voorkeurVoorkeur DROP FOREIGN KEY FK_1A129E324B30D9C4');
		$this->addSql('ALTER TABLE voorkeurCommissie DROP FOREIGN KEY FK_6567316BCF5E72D');
		$this->addSql('ALTER TABLE Document DROP FOREIGN KEY FK_211FE820BCF5E72D');
		$this->addSql('ALTER TABLE forum_delen DROP FOREIGN KEY FK_4D51668FBCF5E72D');
		$this->addSql('ALTER TABLE forum_delen_meldingen DROP FOREIGN KEY FK_7525C01529CCBAD0');
		$this->addSql('ALTER TABLE forum_draden DROP FOREIGN KEY FK_C7DE4CB629CCBAD0');
		$this->addSql('ALTER TABLE forum_draden DROP FOREIGN KEY FK_C7DE4CB6EAAB93BA');
		$this->addSql('ALTER TABLE forum_draden_gelezen DROP FOREIGN KEY FK_A4E3F87ECA4E5E');
		$this->addSql('ALTER TABLE forum_draden_volgen DROP FOREIGN KEY FK_E660A9C9CA4E5E');
		$this->addSql('ALTER TABLE forum_draden_verbergen DROP FOREIGN KEY FK_40739E14CA4E5E');
		$this->addSql('ALTER TABLE forum_posts DROP FOREIGN KEY FK_90291C2DCA4E5E');
		$this->addSql('ALTER TABLE forum_draden DROP FOREIGN KEY FK_C7DE4CB6E196D02C');
		$this->addSql('ALTER TABLE activiteit_deelnemers DROP FOREIGN KEY FK_7F206BAB9EB44EC5');
		$this->addSql('ALTER TABLE bestuurs_leden DROP FOREIGN KEY FK_7BE62A789EB44EC5');
		$this->addSql('ALTER TABLE commissie_leden DROP FOREIGN KEY FK_18A4E69E9EB44EC5');
		$this->addSql('ALTER TABLE ketzer_deelnemers DROP FOREIGN KEY FK_E29708B29EB44EC5');
		$this->addSql('ALTER TABLE kring_leden DROP FOREIGN KEY FK_C1C295369EB44EC5');
		$this->addSql('ALTER TABLE lichting_leden DROP FOREIGN KEY FK_9F803B119EB44EC5');
		$this->addSql('ALTER TABLE ondervereniging_leden DROP FOREIGN KEY FK_7EC7AEBA9EB44EC5');
		$this->addSql('ALTER TABLE groep_leden DROP FOREIGN KEY FK_47D1C06D9EB44EC5');
		$this->addSql('ALTER TABLE verticale_leden DROP FOREIGN KEY FK_52C85C389EB44EC5');
		$this->addSql('ALTER TABLE werkgroep_deelnemers DROP FOREIGN KEY FK_38E14A6B9EB44EC5');
		$this->addSql('ALTER TABLE eetplan DROP FOREIGN KEY FK_EC97E0BBF0C31BC7');
		$this->addSql('ALTER TABLE bewoners DROP FOREIGN KEY FK_62C774019EB44EC5');
		$this->addSql('ALTER TABLE menus DROP FOREIGN KEY FK_727508CF727ACA70');
		$this->addSql('ALTER TABLE peiling_optie DROP FOREIGN KEY FK_C919E5D7B68DF022');
		$this->addSql('ALTER TABLE peiling_stemmen DROP FOREIGN KEY FK_A5E8105B68DF022');
		$this->addSql('ALTER TABLE pin_transactie_match DROP FOREIGN KEY FK_457B997D1D647A75');
		$this->addSql('DROP TABLE login_sessions');
		$this->addSql('DROP TABLE accounts');
		$this->addSql('DROP TABLE login_remember');
		$this->addSql('DROP TABLE profielen');
		$this->addSql('DROP TABLE CiviLog');
		$this->addSql('DROP TABLE CiviSaldo');
		$this->addSql('DROP TABLE mlt_aanmeldingen');
		$this->addSql('DROP TABLE mlt_maaltijden');
		$this->addSql('DROP TABLE mlt_repetities');
		$this->addSql('DROP TABLE mlt_abonnementen');
		$this->addSql('DROP TABLE mlt_archief');
		$this->addSql('DROP TABLE crv_taken');
		$this->addSql('DROP TABLE crv_repetities');
		$this->addSql('DROP TABLE crv_functies');
		$this->addSql('DROP TABLE CiviProduct');
		$this->addSql('DROP TABLE CiviBestellingInhoud');
		$this->addSql('DROP TABLE CiviBestelling');
		$this->addSql('DROP TABLE CiviPrijs');
		$this->addSql('DROP TABLE CiviCategorie');
		$this->addSql('DROP TABLE biebexemplaar');
		$this->addSql('DROP TABLE biebboek');
		$this->addSql('DROP TABLE lidtoestemmingen');
		$this->addSql('DROP TABLE agenda');
		$this->addSql('DROP TABLE agenda_verbergen');
		$this->addSql('DROP TABLE biebauteur');
		$this->addSql('DROP TABLE biebcategorie');
		$this->addSql('DROP TABLE biebbeschrijving');
		$this->addSql('DROP TABLE changelog');
		$this->addSql('DROP TABLE cms_paginas');
		$this->addSql('DROP TABLE voorkeurCommissie');
		$this->addSql('DROP TABLE voorkeurCommissieCategorie');
		$this->addSql('DROP TABLE voorkeurOpmerking');
		$this->addSql('DROP TABLE voorkeurVoorkeur');
		$this->addSql('DROP TABLE crv_kwalificaties');
		$this->addSql('DROP TABLE crv_voorkeuren');
		$this->addSql('DROP TABLE crv_vrijstellingen');
		$this->addSql('DROP TABLE courant');
		$this->addSql('DROP TABLE courantbericht');
		$this->addSql('DROP TABLE debug_log');
		$this->addSql('DROP TABLE Document');
		$this->addSql('DROP TABLE DocumentCategorie');
		$this->addSql('DROP TABLE eetplan');
		$this->addSql('DROP TABLE eetplan_bekenden');
		$this->addSql('DROP TABLE forum_categorien');
		$this->addSql('DROP TABLE forum_delen');
		$this->addSql('DROP TABLE forum_delen_meldingen');
		$this->addSql('DROP TABLE forum_draden');
		$this->addSql('DROP TABLE forum_draden_gelezen');
		$this->addSql('DROP TABLE forum_draden_volgen');
		$this->addSql('DROP TABLE forum_draden_reageren');
		$this->addSql('DROP TABLE forum_draden_verbergen');
		$this->addSql('DROP TABLE forum_posts');
		$this->addSql('DROP TABLE forumplaatjes');
		$this->addSql('DROP TABLE fotos');
		$this->addSql('DROP TABLE fotoalbums');
		$this->addSql('DROP TABLE foto_tags');
		$this->addSql('DROP TABLE GoogleToken');
		$this->addSql('DROP TABLE activiteiten');
		$this->addSql('DROP TABLE activiteit_deelnemers');
		$this->addSql('DROP TABLE besturen');
		$this->addSql('DROP TABLE bestuurs_leden');
		$this->addSql('DROP TABLE commissies');
		$this->addSql('DROP TABLE commissie_leden');
		$this->addSql('DROP TABLE ketzers');
		$this->addSql('DROP TABLE ketzer_deelnemers');
		$this->addSql('DROP TABLE kringen');
		$this->addSql('DROP TABLE kring_leden');
		$this->addSql('DROP TABLE lichtingen');
		$this->addSql('DROP TABLE lichting_leden');
		$this->addSql('DROP TABLE onderverenigingen');
		$this->addSql('DROP TABLE ondervereniging_leden');
		$this->addSql('DROP TABLE groepen');
		$this->addSql('DROP TABLE groep_leden');
		$this->addSql('DROP TABLE verticalen');
		$this->addSql('DROP TABLE verticale_leden');
		$this->addSql('DROP TABLE werkgroepen');
		$this->addSql('DROP TABLE werkgroep_deelnemers');
		$this->addSql('DROP TABLE woonoorden');
		$this->addSql('DROP TABLE bewoners');
		$this->addSql('DROP TABLE instellingen');
		$this->addSql('DROP TABLE lidinstellingen');
		$this->addSql('DROP TABLE memory_scores');
		$this->addSql('DROP TABLE log');
		$this->addSql('DROP TABLE mlt_beoordelingen');
		$this->addSql('DROP TABLE menus');
		$this->addSql('DROP TABLE peiling');
		$this->addSql('DROP TABLE peiling_optie');
		$this->addSql('DROP TABLE peiling_stemmen');
		$this->addSql('DROP TABLE pin_transacties');
		$this->addSql('DROP TABLE pin_transactie_match');
		$this->addSql('DROP TABLE savedquery');
		$this->addSql('DROP TABLE acl');
		$this->addSql('DROP TABLE onetime_tokens');
	}
}
