FROM node:8-alpine

RUN apk add --no-cache \
	autoconf \
	automake \
	g++ \
	libpng-dev \
	libtool \
	make \
	nasm

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

ENTRYPOINT ["yarn"]
CMD ["run", "watch-poll"]
