FROM node:12-alpine

RUN apk add --no-cache \
	git \
	autoconf \
	automake \
	g++ \
	libpng-dev \
	libtool \
	make \
	python \
	nasm

RUN npm install -g cross-env webpack-cli

WORKDIR /app

ENTRYPOINT ["yarn"]
CMD ["run", "docker"]
