FROM php:8.2-apache

# Install system dependencies
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    sendmail \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    imagemagick \
    memcached \
    libmemcached-dev \
    libicu-dev \
    git \
    zlib1g-dev \
    libzip-dev \
    libssl-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install mysqli pdo pdo_mysql exif gd opcache intl zip

# Install xdebug
RUN pecl install xdebug

# Install memcached with explicit configuration
RUN yes '' | pecl install -f memcached-3.2.0 \
  && docker-php-ext-enable memcached

# Enable extensions
RUN docker-php-ext-enable xdebug memcached

# enable apache mods
RUN a2enmod rewrite && a2enmod headers

# copy config
COPY docker/dev/apache2.conf /etc/apache2/apache2.conf
COPY docker/dev/php.ini  /usr/local/etc/php/php.ini
COPY docker/dev/memcached.conf /etc/memcached.conf

RUN mkdir /app && mkdir /app/sessie && mkdir /app/var && chown -R www-data "/app" && chmod -R u+rwx "/app"

CMD service memcached start && apache2-foreground
