FROM node:18-alpine

RUN apk add --no-cache \
	git \
	autoconf \
	automake \
	g++ \
	libpng-dev \
	libtool \
	make \
	python3 \
	nasm

RUN npm install -g cross-env webpack-cli

WORKDIR /app

CMD yarn install && yarn docker
