@startuml
title: Setup van een request
index -> configuratie.include ++
configuratie.include -> bootstrap ++
note over bootstrap
Laad "".env"", "".env.local"", "".env.dev"", etc.
Zie symfony/dotenv
end note
return
configuratie.include -> configuratie.include : Laad error handlers
configuratie.include -> Kernel ++ : ""$kernel->boot()""
note over Kernel
Laad configuratie voor Symfony,
routes, bundles, etc. Zie de
""config"" map hier voor. Zet
ook de database klaar.
Zie https://symfony.com/doc/current/configuration
end note
return
configuratie.include -> configuratie.include : Zet php configuratie
configuratie.include -> LoginService ++ : authenticate()
note over LoginService
Controleert of er een sessie is sessie
met een gebruiker geassocieerd kan worden.
Controleert ook of de sessie of het wachtwoord
nog niet verlopen is.
end note
return
return ""Kernel""
@enduml
