<?php

class helper_plugin_confmanager extends DokuWiki_Plugin {

    public function getConfigFiles() {
        static $configs = null;
        if ($configs === null) {
            $configs = array();
            trigger_event('CONFMANAGER_CONFIGFILES_REGISTER', $configs, null, false);
            usort($configs, array($this, '_sortByConfigName'));
        }
        return $configs;
    }

    /**
     * @param string $id Config ID
     * @return ConfigManagerConfigType
     */
    public function getConfigById($id) {
        foreach ($this->getConfigFiles() as $config) {
            if ($this->getConfigId($config) === $id) {
                return $config;
            }
        }
        return false;
    }

    public function getConfigId(ConfigManagerConfigType $config) {
        $hash = '';
        $paths = $config->getPaths();
        if (count($paths) == 0) return '';

        $hash .= realpath($paths[0]);
        return md5($hash);
    }

    public function areWriteable($files) {
        foreach ($files as $file) {
            if (!is_writable($file)) {
                return false;
            }
        }
        return true;
    }

    public function getCoreConfigHeader() {
        return "# This config was generated by the confmanager plugin.\n"
             . "# Changes made to this file may be overwritten by the plugin.\n"
             . "# Please use the confmanager in the Dokuwiki admin interface.\n";
    }

    public function _sortConf( $k1 , $k2 ) {
        return strlen( $k2 ) - strlen( $k1 );
    }

    public function _sortHuman( $k1 , $k2 ) {
        $k1 = strtolower($k1);
        $k2 = strtolower($k2);
        return strnatcmp($k1,$k2);
    }

    public function _sortByConfigName(ConfigManagerConfigType $left, ConfigManagerConfigType $right) {
        return strnatcasecmp($left->getName(), $right->getName());
    }

    public function tplSaveButton() {
        static $called = false;
        if ($called) {
            return;
        }
        include DOKU_PLUGIN . 'confmanager/tpl/formControls.php';
        $called = true;
    }

    public function prepareEntity($str) {
        $str = trim($str);
        $str = str_replace("\n", '', $str);
        $str = str_replace("\r", '', $str);
        $str = str_replace('#', '\\#', $str);
        return $str;
    }
}

