<?php


namespace CsrDelft\view\bbcode\tag;


use CsrDelft\bb\BbException;
use CsrDelft\bb\BbTag;
use CsrDelft\model\documenten\DocumentModel;
use CsrDelft\model\entity\documenten\Document;
use CsrDelft\model\entity\Plaatje;
use CsrDelft\view\bbcode\BbHelper;

class BbPlaatje extends BbImg {

	public static function getTagName()
	{
		return 'plaatje';
	}


	public function isAllowed()
	{
		return mag("P_LOGGED_IN");
	}
	public function render()
	{
		return parent::render(); // TODO: Change the autogenerated stub
	}

	/**
	 * @param array $arguments
	 */
	public function parse($arguments = [])
	{
		parent::parse($arguments);
		$plaatje = new Plaatje($this->content);
		if (!$plaatje->exists()) {
			throw new BbException("Plaatje bestaat niet");
		}
		$this->content = $plaatje->getUrl();
	}
}
