@startuml

enum GroepStatus {
	ht
	ft
	ot
}

abstract class Groep {
	id : int
	naam : string
	status : GroepStatus
	samenvatting : string
	omschrijving : string
	keuzelijst : string
	maker : Profiel
	leden : GroepLid[]
}

abstract class AgendaGroep extends Groep {
	beginMoment : date?
	eindMoment : date?
	inAgenda : bool
}

abstract class AanmeldGroep extends Groep {
	aanmeldLimiet : int
	aanmeldenVanaf : date?
	aanmeldenTot : date?
}

abstract class AgendaAanmeldGroep extends AanmeldGroep {
	beginMoment : date?
	eindMoment : date?
	inAgenda : bool
}

class Activiteit extends AgendaAanmeldGroep {
}

class Bestuur extends AgendaGroep {
}

class Commissie extends AgendaGroep {
}

class Ketzer extends AanmeldGroep {
}
class Kring extends AgendaGroep {
}
class Lichting extends Groep {
}
class Ondervereniging extends AgendaGroep {
}
class RechtenGroep extends Groep {
}
class Verticale extends Groep {
}
class Werkgroep extends AgendaGroep {
}
class Woonoord extends AgendaGroep {
}

@enduml
