ALTER TABLE `lid` CHANGE `permissies` `permissies` ENUM( 'P_LID', 'P_NOBODY', 'P_PUBCIE', 'P_OUDLID', 'P_MODERATOR', 'P_MAALCIE', 'P_BESTUUR', 'P_KNORRIE', 'P_VAB', 'P_ETER', 'P_BASF' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'P_NOBODY';

