-- phpMyAdmin SQL Dump
-- version 4.0.4.1
-- http://www.phpmyadmin.net
--
-- Machine: 127.0.0.1
-- Genereertijd: 29 nov 2013 om 23:16
-- Serverversie: 5.5.32
-- PHP-versie: 5.4.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Databank: `csrdelft`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `crv_functies`
--

CREATE TABLE IF NOT EXISTS `crv_functies` (
  `functie_id` int(11) NOT NULL AUTO_INCREMENT,
  `naam` varchar(255) NOT NULL,
  `afkorting` varchar(11) NOT NULL,
  `omschrijving` text NOT NULL,
  `email_bericht` text NOT NULL,
  `standaard_punten` int(11) NOT NULL,
  `kwalificatie_benodigd` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`functie_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=12 ;

--
-- Gegevens worden uitgevoerd voor tabel `crv_functies`
--

INSERT INTO `crv_functies` (`functie_id`, `naam`, `afkorting`, `omschrijving`, `email_bericht`, `standaard_punten`, `kwalificatie_benodigd`) VALUES
(1, 'Koken', 'K', '', 'Geachte LIDNAAM,\r\n\r\nU zult op DATUM een heerlijke maaltijd mogen bereiden op Confide.\r\nBijgevoegd stuur ik de instructie voor koks en de handleiding voor de oven.\r\n\r\nDe oven werkt weer in zijn geheel.\r\nDoor het hygiëne-commissariaat is bepaald dat de koks verantwoordelijk zijn voor de schoonmaak van de oven, dus bij deze.\r\nDaarnaast nog een punt om op te letten, alle overgebleven etenswaren moeten worden geveild, niets mag er in de keuken blijven liggen.\r\nLet ook goed op of er mensen mee eten met allergieën, en hou daar rekening mee.\r\n\r\nOvenhandleiding: https://docs.google.com/document/d/1DKyl-jvkTRCd0LnrIPZaLmfRYyWdlYRRiQr9wVhnFF8/edit?hl=en&authkey=CNDuhLoK#\r\nInstructie koks: https://docs.google.com/document/d/1QFLBHqcFNuqp8lYCGCnAXz98qyuf4gb87vSC5IvT3H4/edit?hl=en&authkey=CN_Rj44L#\r\n\r\n\r\n\r\nIk wens u heel veel succes en plezier.\r\n\r\nMet vriendelijke groet,\r\nAm. CorveeCaesar\r\nMatthias Floor\r\n\r\nPS: MEEETEN\r\n\r\n Corvee-rooster: http://csrdelft.nl/actueel/maaltijden/corveerooster/\r\n Corvee-punten: http://csrdelft.nl/actueel/maaltijden/corveepunten/\r\n RKK-punten: https://docs.google.com/spreadsheet/ccc?key=0Ai3inI9swl9odEEzY3ZhcHgzX0h4UGltaUhxUWEtWXc&authkey=CKKMlLAB', 4, 0),
(2, 'Afwassen', 'A', '', 'Geachte LIDNAAM,\r\n\r\nU bent uitverkoren om op DATUM de vaat weer schoon te maken op Confide.\r\n\r\nKWALIAFWASSER De kwali-afwasser is degene die bovenaan in het rooster staat en is eindverantwoordelijke. Hij/zij zal met behulp van jullie allen er voor zorgen dat alle taken die op de afwas-instructie staan uitgevoerd worden.\r\nIk stuur je dan ook mede de instructie voor het afwassen, lees deze goed door.\r\n\r\nInstructies afwas: https://dl.dropboxusercontent.com/u/240485016/Instructie%20Afwassen.pdf\r\n\r\nLet vooral op de volgend punten:\r\n - de braadslede is in z''n geheel ingevet\r\n - vloer schoon, putje schoon.\r\n - de oven, als hij gebruikt is, droog van binnen en ook open\r\n - laat de volle vuilniszakken niet in de service-gang staan maar ruim ze op in het afvalhok\r\n\r\nTips:\r\n - coördineer bij het afruimen van de borden in de keuken en zet het handig neer. Dat scheelt later een hoop werk.\r\n\r\nIk wens u heel veel succes en plezier.\r\n\r\nMet vriendelijke groet,\r\nAm. CorveeCaesar\r\nMatthias Floor\r\n\r\nPS: MEEETEN\r\n\r\n Corvee-rooster: http://csrdelft.nl/actueel/maaltijden/corveerooster/\r\n Corvee-punten: http://csrdelft.nl/actueel/maaltijden/corveepunten/\r\n RKK-punten: https://docs.google.com/spreadsheet/ccc?key=0Ai3inI9swl9odEEzY3ZhcHgzX0h4UGltaUhxUWEtWXc&authkey=CKKMlLAB', 3, 0),
(3, 'Tafelpraeses', 'tP', '', 'Beste LIDNAAM,\r\n\r\nVoor DATUM sta jij ingeroosterd als tafelpraeses.\r\nBij deze een herinnering aan deze eervolle taak! Zorg dat je er om 17:30\r\nbent om alles klaar te zetten, verdere instructies heb ik in de link\r\ngestopt. Veel succes!\r\n\r\nIk moest nog namens het bestuur melden dat de maaltijd niet te lang moet zijn. Zorg ervoor dat u een goede orde tijdens de maaltijd houdt.\r\n\r\nMet vriendelijke groet,\r\nAm. CorveeCaesar\r\nMatthias Floor\r\n\r\nPs. MEEETEN\r\n\r\nInstructie Tafelpraeses:  https://dl.dropboxusercontent.com/u/240485016/Instructie%20Tafelpraesides.pdf', 0, 0),
(4, 'Theedoeken wassen', 'T', '', 'Beste LIDNAAM,\r\n\r\nU bent bevoorrecht om op DATUM de theedoeken van Confide te wassen.\r\nMede stuur ik u de instructie daarvoor.\r\nDe theedoeken moeten maandagmiddag weer schoon terug zijn op Confide.\r\n\r\nInstructies theedoeken: https://dl.dropboxusercontent.com/u/240485016/Instructie%20Theedoeken%20Wassen.pdf\r\n\r\nLet vooral op de volgende punten:\r\n- zorg dat je alle SCHORTEN en theedoeken hebt meegenomen.\r\n- zorg dat ze voor maandagmiddag 3 UUR schoon terug zijn.\r\n\r\nDaarnaast is het BELANGRIJK dat de theedoeken van de Soccie (de Grolsch theedoeken en de donkerblauwe theedoeken) NIET moeten worden meegenomen. Deze kunnen worden neergelegd in de wastas van de Soccie, en die ligt in het onderste kastje achter de voorbar.\r\n\r\nAlvast veel plezier en succes toegewenst,\r\n\r\nMet vriendelijke groet,\r\nAm. CorveeCaesar\r\nMatthias Floor\r\n\r\nPS: MEEETEN\r\n\r\n Corvee-rooster: http://csrdelft.nl/actueel/maaltijden/corveerooster/\r\n Corvee-punten: http://csrdelft.nl/actueel/maaltijden/corveepunten/\r\n RKK-punten: https://docs.google.com/spreadsheet/ccc?key=0Ai3inI9swl9odEEzY3ZhcHgzX0h4UGltaUhxUWEtWXc&authkey=CKKMlLAB', 2, 0),
(5, 'Keuken schoonmaken', 'sK', '', 'Beste LIDNAAM,\r\n\r\nU bent bevoorrecht om op DATUM de keuken schoon te maken.\r\nIn het onderstaande document stuur ik u mede de keuken-schoonmaak-instructie, deze instructie is slechts een richtlijn.\r\n\r\nInstructie keuken schoonmaken:  https://dl.dropboxusercontent.com/u/240485016/Instructie%20Keuken%20Schoonmaken.pdf\r\n\r\nKomt u dus dingen tegen die schoongemaakt moeten worden maar niet specifiek in de instructie staan, maakt u dit dan aub schoon.\r\nVindt u dat er andere dingen zijn die wel specifieker in de instructie moeten komen te staan. Bericht het mij.\r\n\r\nIk wens u heel veel succes en plezier.\r\n\r\nMet vriendelijke groet,\r\nAm. CorveeCaesar\r\nMatthias Floor\r\n\r\n Corvee-rooster: http://csrdelft.nl/actueel/maaltijden/corveerooster/\r\n Corvee-punten: http://csrdelft.nl/actueel/maaltijden/corveepunten/\r\n RKK-punten: https://docs.google.com/spreadsheet/ccc?key=0Ai3inI9swl9odEEzY3ZhcHgzX0h4UGltaUhxUWEtWXc&authkey=CKKMlLAB', 3, 0),
(6, 'Afzuigkap schoonmaken', 'sA', '', 'Geachte LIDNAAM,\r\n\r\nU heeft de eervolle taak om op DATUM de afzuigkappen van de keuken van Confide schoon te maken\r\nMede stuur ik u de instructies voor het schoonmaken van de afzuigkappen.\r\n\r\nInstructies schoonmaken: https://dl.dropboxusercontent.com/u/240485016/Instructie%20Afzuigkappen%20Schoonmaken.pdf\r\n\r\nLet vooral op de volgende zaken:\r\n - De behuizing van de afzuigkappen moet ook schoon worden gemaakt.\r\n - Doordat de vaatwasser erg traag is met opwarmen is het qua tijd verstandiger ze met de hand schoon te maken.\r\n\r\nIk wens u heel veel succes en plezier.\r\n\r\nMet vriendelijke groet,\r\nAm. CorveeCaesar\r\nMatthias Floor\r\n\r\n Corvee-rooster: http://csrdelft.nl/actueel/maaltijden/corveerooster/\r\n Corvee-punten: http://csrdelft.nl/actueel/maaltijden/corveepunten/\r\n RKK-punten: https://docs.google.com/spreadsheet/ccc?key=0Ai3inI9swl9odEEzY3ZhcHgzX0h4UGltaUhxUWEtWXc&authkey=CKKMlLAB', 3, 0),
(7, 'Kwalikok', 'kK', '', 'Geachte LIDNAAM,\r\n\r\nU zult op DATUM een heerlijke maaltijd mogen bereiden op Confide.\r\nBijgevoegd stuur ik de instructie voor koks en de handleiding voor de oven.\r\n\r\nDe oven werkt weer in zijn geheel.\r\nDoor het hygiëne-commissariaat is bepaald dat de koks verantwoordelijk zijn voor de schoonmaak van de oven, dus bij deze.\r\nDaarnaast nog een punt om op te letten, alle overgebleven etenswaren moeten worden geveild, niets mag er in de keuken blijven liggen.\r\nLet ook goed op of er mensen mee eten met allergieën, en hou daar rekening mee.\r\n\r\nOvenhandleiding: https://docs.google.com/document/d/1DKyl-jvkTRCd0LnrIPZaLmfRYyWdlYRRiQr9wVhnFF8/edit?hl=en&authkey=CNDuhLoK#\r\nInstructie koks: https://docs.google.com/document/d/1QFLBHqcFNuqp8lYCGCnAXz98qyuf4gb87vSC5IvT3H4/edit?hl=en&authkey=CN_Rj44L#\r\n\r\n\r\n\r\nIk wens u heel veel succes en plezier.\r\n\r\nMet vriendelijke groet,\r\nAm. CorveeCaesar\r\nMatthias Floor\r\n\r\nPS: MEEETEN\r\n\r\n Corvee-rooster: http://csrdelft.nl/actueel/maaltijden/corveerooster/\r\n Corvee-punten: http://csrdelft.nl/actueel/maaltijden/corveepunten/\r\n RKK-punten: https://docs.google.com/spreadsheet/ccc?key=0Ai3inI9swl9odEEzY3ZhcHgzX0h4UGltaUhxUWEtWXc&authkey=CKKMlLAB', 1, 0),
(8, 'Kwaliafwasser', 'kA', '', 'Geachte LIDNAAM,\r\n\r\nU bent uitverkoren om op DATUM de vaat weer schoon te maken op Confide.\r\n\r\nKWALIAFWASSER De kwali-afwasser is degene die bovenaan in het rooster staat en is eindverantwoordelijke. Hij/zij zal met behulp van jullie allen er voor zorgen dat alle taken die op de afwas-instructie staan uitgevoerd worden.\r\nIk stuur je dan ook mede de instructie voor het afwassen, lees deze goed door.\r\n\r\nInstructies afwas: https://dl.dropboxusercontent.com/u/240485016/Instructie%20Afwassen.pdf\r\n\r\nLet vooral op de volgend punten:\r\n - de braadslede is in z''n geheel ingevet\r\n - vloer schoon, putje schoon.\r\n - de oven, als hij gebruikt is, droog van binnen en ook open\r\n - laat de volle vuilniszakken niet in de service-gang staan maar ruim ze op in het afvalhok\r\n\r\nTips:\r\n - coördineer bij het afruimen van de borden in de keuken en zet het handig neer. Dat scheelt later een hoop werk.\r\n\r\nIk wens u heel veel succes en plezier.\r\n\r\nMet vriendelijke groet,\r\nAm. CorveeCaesar\r\nMatthias Floor\r\n\r\nPS: MEEETEN\r\n\r\n Corvee-rooster: http://csrdelft.nl/actueel/maaltijden/corveerooster/\r\n Corvee-punten: http://csrdelft.nl/actueel/maaltijden/corveepunten/\r\n RKK-punten: https://docs.google.com/spreadsheet/ccc?key=0Ai3inI9swl9odEEzY3ZhcHgzX0h4UGltaUhxUWEtWXc&authkey=CKKMlLAB', 3, 0),
(9, 'Frituur schoonmaken', 'sF', '', 'Beste LIDNAAM,\r\n\r\nU heeft de eervolle taak om op DATUM zorg te dragen voor het schoonmaken van de vetput.\r\nMede stuur ik je de instructie voor het schoonmaken.\r\nDeze taak mag ook een paar dagen eerder worden uitgevoerd maar zorg wel dat de vetput voor vrijdagavond schoon is.\r\n\r\nInstructies frituur schoonmaken:  https://dl.dropboxusercontent.com/u/240485016/Instructie%20Frituur%20Schoonmaken.pdf\r\n\r\nLet vooral op de volgende punten:\r\n - Trek oude kleren aan\r\n - Mors niet (te veel)\r\n - Maak alles goed schoon nadien\r\n\r\nMet vriendelijke groet,\r\nAm. CorveeCaesar\r\nMatthias Floor\r\n\r\n Corvee-rooster: http://csrdelft.nl/actueel/maaltijden/corveerooster/\r\n Corvee-punten: http://csrdelft.nl/actueel/maaltijden/corveepunten/\r\n RKK-punten: https://docs.google.com/spreadsheet/ccc?key=0Ai3inI9swl9odEEzY3ZhcHgzX0h4UGltaUhxUWEtWXc&authkey=CKKMlLAB', 2, 0),
(10, 'Klussen (licht)', 'Kli', '', 'Beste LIDNAAM, \r\n\r\nU bent bevoorrecht om op DATUM licht te komen klussen. De ViP zal u nader instrueren. Ik wens u heel veel succes en plezier. \r\n\r\nMet vriendelijke groet,\r\nAm. CorveeCaesar\r\n\r\nook namens de OnderhoudCieP en de ViP', 2, 0),
(11, 'Klussen (zwaar)', 'Kzw', '', 'Beste LIDNAAM, \r\n\r\nU bent bevoorrecht om op DATUM zwaar te komen klussen. De ViP zal u nader instrueren. Ik wens u heel veel succes en plezier. \r\n\r\nMet vriendelijke groet, Am. CorveeCaesar\r\n\r\nook namens de OnderhoudCieP en de ViP', 3, 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
