ALTER TABLE `menu` CHANGE `ID` `menu_id` INT( 11 ) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `menu` CHANGE `pID` `parent_id` INT( 11 ) NOT NULL DEFAULT '0';
ALTER TABLE `menu` CHANGE `zichtbaar` `zichtbaar` BOOLEAN NOT NULL DEFAULT TRUE ;
ALTER TABLE `menu` CHANGE `permission` `permission` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'P_NOBODY';
ALTER TABLE `menu` CHANGE `link` `link` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ;
ALTER TABLE `menu` CHANGE `gasnelnaar` `menu` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'main';
INSERT INTO `menu` ( `menu_id` , `parent_id` , `prioriteit` , `tekst` , `link` , `permission` , `zichtbaar` , `menu` ) SELECT NULL , parent_id, prioriteit, tekst, link, permission, zichtbaar, 'gasnelnaar' FROM menu WHERE menu = 'ja';
UPDATE menu SET zichtbaar = TRUE WHERE zichtbaar >0;
UPDATE menu SET menu = 'main' WHERE menu != 'gasnelnaar';
UPDATE menu SET `menu` = 'gasnelnaar',zichtbaar = FALSE WHERE tekst LIKE 'Noviet toevoegen';
DELETE FROM menu WHERE tekst LIKE 'BOT 2009';
DELETE FROM menu WHERE tekst LIKE 'Corveerooster' AND menu = 'main';
UPDATE menu SET `parent_id` = 0 WHERE menu = 'gasnelnaar';
UPDATE menu SET `parent_id` = 0,menu='beheer' WHERE parent_id>4;
UPDATE menu SET zichtbaar = FALSE WHERE tekst LIKE 'OWee' OR tekst LIKE 'Dies' OR tekst LIKE 'Lustrum';