ALTER TABLE `lid` CHANGE `permissies` `permissies` ENUM( 'P_LID', 'P_NOBODY', 'P_PUBCIE', 'P_OUDLID', 'P_MODERATOR', 'P_MAALCIE', 'P_BESTUUR', 'P_KNORRIE', 'P_VAB', 'P_ETER', 'P_BASF', 'R_LID', 'R_NOBODY', 'R_PUBCIE', 'R_OUDLID', 'R_MODERATOR', 'R_MAALCIE', 'R_BESTUUR', 'R_KNORRIE', 'R_VAB', 'R_ETER', 'R_BASF' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'P_NOBODY';
UPDATE lid SET permissies = 'R_LID' WHERE permissies = 'P_LID';
UPDATE lid SET permissies = 'R_NOBODY' WHERE permissies = 'P_NOBODY';
UPDATE lid SET permissies = 'R_PUBCIE' WHERE permissies = 'P_PUBCIE';
UPDATE lid SET permissies = 'R_OUDLID' WHERE permissies = 'P_OUDLID';
UPDATE lid SET permissies = 'R_MODERATOR' WHERE permissies = 'P_MODERATOR';
UPDATE lid SET permissies = 'R_MAALCIE' WHERE permissies = 'P_MAALCIE';
UPDATE lid SET permissies = 'R_BESTUUR' WHERE permissies = 'P_BESTUUR';
UPDATE lid SET permissies = 'R_KNORRIE' WHERE permissies = 'P_KNORRIE';
UPDATE lid SET permissies = 'R_VAB' WHERE permissies = 'P_VAB';
UPDATE lid SET permissies = 'R_ETER' WHERE permissies = 'P_ETER';
UPDATE lid SET permissies = 'R_BASF' WHERE permissies = 'P_BASF';
ALTER TABLE `lid` CHANGE `permissies` `permissies` ENUM( 'R_LID', 'R_NOBODY', 'R_PUBCIE', 'R_OUDLID', 'R_MODERATOR', 'R_MAALCIE', 'R_BESTUUR', 'R_KNORRIE', 'R_VAB', 'R_ETER', 'R_BASF' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'R_NOBODY';