ALTER TABLE lidinstellingen CHANGE lid_id uid varchar(4) NOT NULL;
ALTER TABLE debug_log CHANGE lid_id uid varchar(4);
ALTER TABLE `debug_log` CHANGE `su_id` `su_uid` VARCHAR(4);
ALTER TABLE `crv_kwalificaties` CHANGE `lid_id` `uid` VARCHAR(4) NOT NULL;
ALTER TABLE `crv_taken` CHANGE `lid_id` `uid` VARCHAR(4);
ALTER TABLE `crv_voorkeuren` CHANGE `lid_id` `uid` VARCHAR(4) NOT NULL;
ALTER TABLE `crv_vrijstellingen` CHANGE `lid_id` `uid` VARCHAR(4) NOT NULL;
ALTER TABLE `forum_delen` CHANGE `laatste_lid_id` `laatste_wijziging_uid` VARCHAR(4);
ALTER TABLE `forum_draden` CHANGE `lid_id` `uid` VARCHAR(4) NOT NULL;
ALTER TABLE `forum_draden` CHANGE `laatste_lid_id` `laatste_wijziging_uid` VARCHAR(4);
ALTER TABLE `forum_draden_gelezen` CHANGE `lid_id` `uid` VARCHAR(4) NOT NULL;
ALTER TABLE `forum_draden_verbergen` CHANGE `lid_id` `uid` VARCHAR(4) NOT NULL;
ALTER TABLE `forum_draden_volgen` CHANGE `lid_id` `uid` VARCHAR(4) NOT NULL;
ALTER TABLE `forum_posts` CHANGE `lid_id` `uid` VARCHAR(4) NOT NULL;
ALTER TABLE `mlt_aanmeldingen` CHANGE `lid_id` `uid` VARCHAR(4) NOT NULL;
ALTER TABLE `mlt_abonnementen` CHANGE `lid_id` `uid` VARCHAR(4) NOT NULL;
