ALTER TABLE `lid` CHANGE `voorletters` `voorletters` VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE `lid` CHANGE `echtgenoot` `echtgenoot` VARCHAR(4) NULL DEFAULT NULL;
ALTER TABLE `lid` CHANGE `adresseringechtpaar` `adresseringechtpaar` VARCHAR(250) NULL DEFAULT NULL COMMENT 'Tenaamstelling van post gericht aan het echtpaar';
ALTER TABLE `lid` CHANGE `linkedin` `linkedin` VARCHAR(80) NOT NULL DEFAULT '' COMMENT 'link naar LinkedIn-profiel';
ALTER TABLE `lid` CHANGE `beroep` `beroep` TEXT NULL;
ALTER TABLE `lid` CHANGE `patroon` `patroon` VARCHAR(4) NOT NULL DEFAULT '';
ALTER TABLE `lid` CHANGE `studienr` `studienr` VARCHAR(20) NULL DEFAULT NULL;
ALTER TABLE `lid` CHANGE `lidafdatum` `lidafdatum` DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE `lid` CHANGE `sterfdatum` `sterfdatum` DATE NOT NULL DEFAULT '0000-00-00';
ALTER TABLE `lid` CHANGE `verticale` `verticale` INT(4) NOT NULL DEFAULT '0';
ALTER TABLE `lid` CHANGE `eetwens` `eetwens` TEXT NULL DEFAULT NULL;
ALTER TABLE `lid` CHANGE `corvee_punten` `corvee_punten` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `lid` CHANGE `corvee_punten_bonus` `corvee_punten_bonus` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `lid` CHANGE `kgb` `kgb` TEXT NULL DEFAULT NULL;
ALTER TABLE `lid` CHANGE `rssToken` `rssToken` VARCHAR(25) NULL DEFAULT NULL COMMENT 'Zonder ingelogged te zijn toch volledig rss-feed weergeven';
ALTER TABLE `lid` CHANGE `ovkaart` `ovkaart` VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE `lid` CHANGE `zingen` `zingen` VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE `lid` CHANGE `novitiaat` `novitiaat` TEXT NULL DEFAULT NULL;
ALTER TABLE `lid` CHANGE `lengte` `lengte` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `lid` CHANGE `vrienden` `vrienden` VARCHAR(300) NOT NULL DEFAULT '';
ALTER TABLE `lid` CHANGE `middelbareSchool` `middelbareSchool` VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE `lid` CHANGE `novietSoort` `novietSoort` VARCHAR(15) NOT NULL DEFAULT '';
ALTER TABLE `lid` CHANGE `matrixPlek` `matrixPlek` VARCHAR(15) NOT NULL DEFAULT '';
ALTER TABLE `lid` CHANGE `startkamp` `startkamp` VARCHAR(10) NOT NULL DEFAULT '';
ALTER TABLE `lid` CHANGE `medisch` `medisch` TEXT NULL DEFAULT NULL;
ALTER TABLE `lid` CHANGE `novitiaatBijz` `novitiaatBijz` TEXT NULL DEFAULT NULL;