ALTER TABLE verticalen DROP id;
ALTER TABLE lid DROP forum_name;
ALTER TABLE lid DROP forum_postsortering;
UPDATE `lid` SET verticale = '_' WHERE verticale = '0';
UPDATE `lid` SET verticale = 'A' WHERE verticale = '1';
UPDATE `lid` SET verticale = 'B' WHERE verticale = '2';
UPDATE `lid` SET verticale = 'C' WHERE verticale = '3';
UPDATE `lid` SET verticale = 'D' WHERE verticale = '4';
UPDATE `lid` SET verticale = 'E' WHERE verticale = '5';
UPDATE `lid` SET verticale = 'F' WHERE verticale = '6';
UPDATE `lid` SET verticale = 'G' WHERE verticale = '7';
UPDATE `lid` SET verticale = 'H' WHERE verticale = '8';
UPDATE `lid` SET verticale = 'I' WHERE verticale = '9';