name: Psalm Static analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          composer_ignore_platform_reqs: true
          composer_require_dev: true
          security_analysis: true
          report_file: results.sarif

      - name: Upload Security Analysis results to GitHub
        if: github.repository == 'csrdelft/csrdelft.nl'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
